import {beforeEach,expect,it,vi} from 'vitest';
vi.mock('server-only',()=>({}));
const m=vi.hoisted(()=>({session:vi.fn(),state:vi.fn(),quota:vi.fn(),complete:vi.fn(),upsert:vi.fn(),result:{data:null as unknown,error:null},filters:[] as unknown[][],updates:[] as unknown[]}));
vi.mock('@/lib/rcv3/access',()=>({session:m.session,input:async(r:Request)=>JSON.parse(await r.text()),reply:(d:unknown)=>Response.json(d),failure:(e:Error)=>Response.json({code:e.message},{status:400})}));
vi.mock('@/lib/rcv3/answer-language',()=>({accountAnswerLanguage:async()=> 'en'}));
vi.mock('@/lib/ai/connectors',()=>({getAvailableProviderIds:()=>['openai'],getConnector:()=>({complete:m.complete})}));
vi.mock('@/lib/rcv3/learning/store',()=>({tables:{progress:'p',attempts:'a',projects:'w'},learningState:m.state,reserveLearning:m.quota,learningDB:()=>({from:()=>{const q={select:()=>q,eq:(...v:unknown[])=>{m.filters.push(v);return q;},is:()=>q,gte:()=>q,order:()=>q,limit:()=>q,maybeSingle:async()=>m.result,insert:async()=>({error:null}),upsert:m.upsert,update:(v:unknown)=>{m.updates.push(v);return q;},then:(resolve:(x:unknown)=>void)=>Promise.resolve(m.result).then(resolve)};return q;}})}));
import {POST} from './route';
import {lessons} from '@/lib/rcv3/learning/course';
import {examQuestions,practiceQuestion} from '@/lib/rcv3/learning/questions';
const id='00000000-0000-4000-8000-000000000001';
const req=(data:unknown)=>new Request('https://preview.test/api/rcv3/learn',{method:'POST',body:JSON.stringify(data)});
beforeEach(()=>{vi.clearAllMocks();m.upsert.mockResolvedValue({error:null});m.filters=[];m.updates=[];m.result={data:null,error:null};m.session.mockResolvedValue({user:{id:'owner',fullName:'Test Learner'}});m.state.mockResolvedValue({completed:lessons.map(l=>l.id),certificate:null});});
it('requires a signed-in user',async()=>{m.session.mockRejectedValue(new Error('RCV3_AUTH'));expect((await (await POST(req({action:'start'}))).json()).code).toBe('RCV3_AUTH');});
it('requires every lesson before opening an exam',async()=>{m.state.mockResolvedValue({completed:[],certificate:null});expect((await (await POST(req({action:'start'}))).json()).code).toBe('RCV3_LESSONS_REQUIRED');expect(m.quota).not.toHaveBeenCalled();});
it('rejects missing or foreign attempts with owner-scoped lookup',async()=>{const r=await POST(req({action:'submit',attempt:id,answers:Array(30).fill(0)}));expect((await r.json()).code).toBe('RCV3_NOT_FOUND');expect(m.filters).toContainEqual(['owner_id','owner']);expect(m.updates).toHaveLength(0);});
it('does not regrade a submitted attempt',async()=>{m.result={data:{submitted_at:new Date().toISOString(),score:70},error:null};const r=await POST(req({action:'submit',attempt:id,answers:Array(30).fill(0)}));expect((await r.json()).score).toBe(70);expect(m.updates).toHaveLength(0);});
it('enforces quota before creating another exam',async()=>{m.result={data:[],error:null};m.quota.mockRejectedValue(new Error('RCV3_LIMIT'));expect((await (await POST(req({action:'start'}))).json()).code).toBe('RCV3_LIMIT');});
it('practice failure does not mark a lesson complete',async()=>{const r=await POST(req({action:'practice',lesson:'001',answer:(practiceQuestion('001').answer+1)%3}));expect((await r.json()).correct).toBe(false);});
it('server-created public exam contains thirty questions without answers',async()=>{m.result={data:[],error:null};m.quota.mockResolvedValue(undefined);const d=await (await POST(req({action:'start'}))).json();expect(d.questions).toHaveLength(30);expect(d.questions[0]).not.toHaveProperty('answer');expect(examQuestions(()=>0)).toHaveLength(30);});

it('rejects advanced completion through the simple quiz',async()=>{const d=await(await POST(req({action:'practice',lesson:'051',answer:0}))).json();expect(d.code).toBe('RCV3_PROJECT_REQUIRED');});
it('rejects an expired exam without changing score',async()=>{m.result={data:{submitted_at:null,created_at:new Date(Date.now()-1800001).toISOString(),questions:examQuestions(()=>0).map(q=>q.id)},error:null};const d=await(await POST(req({action:'submit',attempt:id,answers:Array(30).fill(0)}))).json();expect(d.code).toBe('RCV3_EXAM_EXPIRED');expect(m.updates).toHaveLength(0);});
it('preserves already passed assignment evidence',async()=>{const d=await(await POST(req({action:'project',lesson:'051',artifact:'Evidence '.repeat(25)}))).json();expect(d.code).toBe('RCV3_ALREADY_COMPLETED');expect(m.quota).not.toHaveBeenCalled();});

it('scores a submitted assignment on the server and persists only for its owner',async()=>{m.state.mockResolvedValue({completed:[],certificate:null});m.complete.mockResolvedValue({content:JSON.stringify({relevance:20,completeness:20,verification:20,clarity:20,feedback:'Good evidence.'})});const d=await(await POST(req({action:'project',lesson:'061',artifact:'Fictional company report with assumptions and checks. '.repeat(5)}))).json();expect(d.projectScore).toBe(80);expect(m.upsert).toHaveBeenCalledWith(expect.objectContaining({owner_id:'owner',lesson:'061',score:80}),expect.anything());});
it('rejects malformed AI grades without saving completion',async()=>{m.state.mockResolvedValue({completed:[],certificate:null});m.complete.mockResolvedValue({content:'{"score":100}'});await POST(req({action:'project',lesson:'061',artifact:'Fictional company report '.repeat(20)}));expect(m.upsert).not.toHaveBeenCalled();});
it('issues a certificate only from a passing server grade',async()=>{const qs=examQuestions(()=>0);m.result={data:{submitted_at:null,created_at:new Date().toISOString(),questions:qs.map(q=>q.id),length:1},error:null};const answers=qs.map((q,i)=>i<9?(q.answer+1)%3:q.answer);const d=await(await POST(req({action:'submit',attempt:id,answers}))).json();expect(d.score).toBe(70);expect(d.passed).toBe(true);expect(m.updates[0]).toMatchObject({score:70,certificate_id:expect.any(String)});});
