import {beforeEach,afterEach,it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({access:vi.fn(),reserve:vi.fn(),paid:vi.fn(),translate:vi.fn()}));
vi.mock('@/lib/rcv3/access',async()=>{const actual=await vi.importActual<typeof import('@/lib/rcv3/access')>('@/lib/rcv3/access');return {...actual,access:m.access};});
vi.mock('@/lib/rcv3/execution',()=>({reserve:m.reserve}));
vi.mock('@/lib/rcv3/checkout-ledger',()=>({requirePaidService:m.paid}));
vi.mock('@/lib/rcv3/speech-language',()=>({speechTextInLanguage:m.translate}));
import {POST} from './route';
function request(extra:Record<string,unknown>={}){return new Request('https://preview.test/api/rcv3/meetings/translate',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://preview.test'},body:JSON.stringify({roomId:'10000000-0000-4000-8000-000000000001',requestId:'20000000-0000-4000-8000-000000000001',source:'ko',target:'en',direction:'outgoing',voice:false,text:'안녕하세요',...extra})});}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('OPENAI_API_KEY','test');m.access.mockResolvedValue({entitlement:null,user:{id:'owner'}});m.reserve.mockResolvedValue(undefined);m.translate.mockResolvedValue('Hello');vi.stubGlobal('fetch',vi.fn(async()=>new Response('audio')));});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
it('outgoing always produces translated speech, never original speech',async()=>{const r=await POST(request());expect(r.status).toBe(200);expect(await r.json()).toMatchObject({original:'안녕하세요',translated:'Hello',audio:Buffer.from('audio').toString('base64')});expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).input).toBe('Hello');});
it('incoming text only makes no speech call',async()=>{const r=await POST(request({direction:'incoming',source:'en',target:'ko',voice:false}));expect(r.status).toBe(200);expect(fetch).not.toHaveBeenCalled();expect((await r.json()).audio).toBeNull();});
it('incoming voice plus text returns both',async()=>{const r=await POST(request({direction:'incoming',voice:true}));expect((await r.json()).audio).toBeTruthy();expect(fetch).toHaveBeenCalledOnce();});
it('refuses inaccessible room before provider calls',async()=>{m.access.mockRejectedValue(new Error('RCV3_NOT_FOUND'));expect((await POST(request())).status).toBe(404);expect(m.reserve).not.toHaveBeenCalled();expect(m.translate).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
it('enforces paid capability and quota before providers',async()=>{m.paid.mockImplementationOnce(()=>{throw new Error('RCV3_SERVICE_NOT_INCLUDED');});expect((await POST(request())).status).toBe(503);expect(m.translate).not.toHaveBeenCalled();m.reserve.mockRejectedValueOnce(new Error('RCV3_LIMIT'));expect((await POST(request())).status).toBe(429);expect(m.translate).not.toHaveBeenCalled();});
it('rejects invalid languages and cross-origin requests',async()=>{expect((await POST(request({target:'unknown'}))).status).toBe(400);const r=request();r.headers.set('Origin','https://other.test');expect((await POST(r)).status).toBe(503);expect(m.access).not.toHaveBeenCalled();});
it('keeps translated captions if synthesis fails; never substitutes original audio',async()=>{vi.mocked(fetch).mockResolvedValue(new Response('',{status:503}));const r=await POST(request());expect((await r.json()).audio).toBeNull();});
it('passes selected source language to transcription',async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json({text:'Hello'})).mockResolvedValueOnce(new Response('translated audio'));expect((await POST(request({text:undefined,audio:Buffer.alloc(120,1).toString('base64'),mime:'audio/webm',source:'en',target:'ko'}))).status).toBe(200);const form=vi.mocked(fetch).mock.calls[0][1]!.body as FormData;expect(form.get('language')).toBe('en');expect(m.translate).toHaveBeenCalledWith('Hello','ko','test',expect.any(AbortSignal));});
