export type CountryRoomPreset = {
  id: string;
  label: string;
  languageTag: string;
  timeZone: string;
  currencyCode: string;
};

// Base locale defaults only. These presets do NOT imply legal, regulatory,
// residency, payment, tax, or provider compliance approval for a country.
export const COUNTRY_ROOM_PRESETS: readonly CountryRoomPreset[] = [
  { id: "AU", label: "Australia", languageTag: "en-AU", timeZone: "Australia/Sydney", currencyCode: "AUD" },
  { id: "KR", label: "South Korea", languageTag: "ko-KR", timeZone: "Asia/Seoul", currencyCode: "KRW" },
  { id: "US", label: "United States", languageTag: "en-US", timeZone: "America/New_York", currencyCode: "USD" },
  { id: "GB", label: "United Kingdom", languageTag: "en-GB", timeZone: "Europe/London", currencyCode: "GBP" },
  { id: "JP", label: "Japan", languageTag: "ja-JP", timeZone: "Asia/Tokyo", currencyCode: "JPY" },
  { id: "SG", label: "Singapore", languageTag: "en-SG", timeZone: "Asia/Singapore", currencyCode: "SGD" },
  { id: "NZ", label: "New Zealand", languageTag: "en-NZ", timeZone: "Pacific/Auckland", currencyCode: "NZD" },
  { id: "CA", label: "Canada", languageTag: "en-CA", timeZone: "America/Toronto", currencyCode: "CAD" },
  { id: "IN", label: "India", languageTag: "en-IN", timeZone: "Asia/Kolkata", currencyCode: "INR" },
  { id: "AE", label: "United Arab Emirates", languageTag: "ar-AE", timeZone: "Asia/Dubai", currencyCode: "AED" },
  { id: "CN", label: "China", languageTag: "zh-CN", timeZone: "Asia/Shanghai", currencyCode: "CNY" },
  { id: "HK", label: "Hong Kong", languageTag: "zh-HK", timeZone: "Asia/Hong_Kong", currencyCode: "HKD" },
  { id: "TW", label: "Taiwan", languageTag: "zh-TW", timeZone: "Asia/Taipei", currencyCode: "TWD" },
  { id: "VN", label: "Vietnam", languageTag: "vi-VN", timeZone: "Asia/Ho_Chi_Minh", currencyCode: "VND" },
  { id: "TH", label: "Thailand", languageTag: "th-TH", timeZone: "Asia/Bangkok", currencyCode: "THB" },
  { id: "MY", label: "Malaysia", languageTag: "ms-MY", timeZone: "Asia/Kuala_Lumpur", currencyCode: "MYR" },
  { id: "ID", label: "Indonesia", languageTag: "id-ID", timeZone: "Asia/Jakarta", currencyCode: "IDR" },
  { id: "PH", label: "Philippines", languageTag: "en-PH", timeZone: "Asia/Manila", currencyCode: "PHP" },
  { id: "BD", label: "Bangladesh", languageTag: "bn-BD", timeZone: "Asia/Dhaka", currencyCode: "BDT" },
  { id: "PK", label: "Pakistan", languageTag: "ur-PK", timeZone: "Asia/Karachi", currencyCode: "PKR" },
  { id: "LK", label: "Sri Lanka", languageTag: "si-LK", timeZone: "Asia/Colombo", currencyCode: "LKR" },
  { id: "NP", label: "Nepal", languageTag: "ne-NP", timeZone: "Asia/Kathmandu", currencyCode: "NPR" },
  { id: "MM", label: "Myanmar", languageTag: "my-MM", timeZone: "Asia/Yangon", currencyCode: "MMK" },
  { id: "KH", label: "Cambodia", languageTag: "km-KH", timeZone: "Asia/Phnom_Penh", currencyCode: "KHR" },
  { id: "LA", label: "Laos", languageTag: "lo-LA", timeZone: "Asia/Vientiane", currencyCode: "LAK" },
  { id: "MN", label: "Mongolia", languageTag: "mn-MN", timeZone: "Asia/Ulaanbaatar", currencyCode: "MNT" },
  { id: "KZ", label: "Kazakhstan", languageTag: "kk-KZ", timeZone: "Asia/Almaty", currencyCode: "KZT" },
  { id: "UZ", label: "Uzbekistan", languageTag: "uz-UZ", timeZone: "Asia/Tashkent", currencyCode: "UZS" },
  { id: "AZ", label: "Azerbaijan", languageTag: "az-AZ", timeZone: "Asia/Baku", currencyCode: "AZN" },
  { id: "GE", label: "Georgia", languageTag: "ka-GE", timeZone: "Asia/Tbilisi", currencyCode: "GEL" },
  { id: "AM", label: "Armenia", languageTag: "hy-AM", timeZone: "Asia/Yerevan", currencyCode: "AMD" },
  { id: "SA", label: "Saudi Arabia", languageTag: "ar-SA", timeZone: "Asia/Riyadh", currencyCode: "SAR" },
  { id: "QA", label: "Qatar", languageTag: "ar-QA", timeZone: "Asia/Qatar", currencyCode: "QAR" },
  { id: "KW", label: "Kuwait", languageTag: "ar-KW", timeZone: "Asia/Kuwait", currencyCode: "KWD" },
  { id: "BH", label: "Bahrain", languageTag: "ar-BH", timeZone: "Asia/Bahrain", currencyCode: "BHD" },
  { id: "OM", label: "Oman", languageTag: "ar-OM", timeZone: "Asia/Muscat", currencyCode: "OMR" },
  { id: "JO", label: "Jordan", languageTag: "ar-JO", timeZone: "Asia/Amman", currencyCode: "JOD" },
  { id: "LB", label: "Lebanon", languageTag: "ar-LB", timeZone: "Asia/Beirut", currencyCode: "LBP" },
  { id: "IL", label: "Israel", languageTag: "he-IL", timeZone: "Asia/Jerusalem", currencyCode: "ILS" },
  { id: "IQ", label: "Iraq", languageTag: "ar-IQ", timeZone: "Asia/Baghdad", currencyCode: "IQD" },
  { id: "TR", label: "Türkiye", languageTag: "tr-TR", timeZone: "Europe/Istanbul", currencyCode: "TRY" },
  { id: "DE", label: "Germany", languageTag: "de-DE", timeZone: "Europe/Berlin", currencyCode: "EUR" },
  { id: "FR", label: "France", languageTag: "fr-FR", timeZone: "Europe/Paris", currencyCode: "EUR" },
  { id: "IT", label: "Italy", languageTag: "it-IT", timeZone: "Europe/Rome", currencyCode: "EUR" },
  { id: "ES", label: "Spain", languageTag: "es-ES", timeZone: "Europe/Madrid", currencyCode: "EUR" },
  { id: "PT", label: "Portugal", languageTag: "pt-PT", timeZone: "Europe/Lisbon", currencyCode: "EUR" },
  { id: "NL", label: "Netherlands", languageTag: "nl-NL", timeZone: "Europe/Amsterdam", currencyCode: "EUR" },
  { id: "BE", label: "Belgium", languageTag: "nl-BE", timeZone: "Europe/Brussels", currencyCode: "EUR" },
  { id: "LU", label: "Luxembourg", languageTag: "fr-LU", timeZone: "Europe/Luxembourg", currencyCode: "EUR" },
  { id: "IE", label: "Ireland", languageTag: "en-IE", timeZone: "Europe/Dublin", currencyCode: "EUR" },
  { id: "CH", label: "Switzerland", languageTag: "de-CH", timeZone: "Europe/Zurich", currencyCode: "CHF" },
  { id: "AT", label: "Austria", languageTag: "de-AT", timeZone: "Europe/Vienna", currencyCode: "EUR" },
  { id: "SE", label: "Sweden", languageTag: "sv-SE", timeZone: "Europe/Stockholm", currencyCode: "SEK" },
  { id: "NO", label: "Norway", languageTag: "nb-NO", timeZone: "Europe/Oslo", currencyCode: "NOK" },
  { id: "DK", label: "Denmark", languageTag: "da-DK", timeZone: "Europe/Copenhagen", currencyCode: "DKK" },
  { id: "FI", label: "Finland", languageTag: "fi-FI", timeZone: "Europe/Helsinki", currencyCode: "EUR" },
  { id: "IS", label: "Iceland", languageTag: "is-IS", timeZone: "Atlantic/Reykjavik", currencyCode: "ISK" },
  { id: "PL", label: "Poland", languageTag: "pl-PL", timeZone: "Europe/Warsaw", currencyCode: "PLN" },
  { id: "CZ", label: "Czechia", languageTag: "cs-CZ", timeZone: "Europe/Prague", currencyCode: "CZK" },
  { id: "SK", label: "Slovakia", languageTag: "sk-SK", timeZone: "Europe/Bratislava", currencyCode: "EUR" },
  { id: "HU", label: "Hungary", languageTag: "hu-HU", timeZone: "Europe/Budapest", currencyCode: "HUF" },
  { id: "RO", label: "Romania", languageTag: "ro-RO", timeZone: "Europe/Bucharest", currencyCode: "RON" },
  { id: "BG", label: "Bulgaria", languageTag: "bg-BG", timeZone: "Europe/Sofia", currencyCode: "BGN" },
  { id: "GR", label: "Greece", languageTag: "el-GR", timeZone: "Europe/Athens", currencyCode: "EUR" },
  { id: "HR", label: "Croatia", languageTag: "hr-HR", timeZone: "Europe/Zagreb", currencyCode: "EUR" },
  { id: "SI", label: "Slovenia", languageTag: "sl-SI", timeZone: "Europe/Ljubljana", currencyCode: "EUR" },
  { id: "RS", label: "Serbia", languageTag: "sr-RS", timeZone: "Europe/Belgrade", currencyCode: "RSD" },
  { id: "BA", label: "Bosnia and Herzegovina", languageTag: "bs-BA", timeZone: "Europe/Sarajevo", currencyCode: "BAM" },
  { id: "AL", label: "Albania", languageTag: "sq-AL", timeZone: "Europe/Tirane", currencyCode: "ALL" },
  { id: "MK", label: "North Macedonia", languageTag: "mk-MK", timeZone: "Europe/Skopje", currencyCode: "MKD" },
  { id: "EE", label: "Estonia", languageTag: "et-EE", timeZone: "Europe/Tallinn", currencyCode: "EUR" },
  { id: "LV", label: "Latvia", languageTag: "lv-LV", timeZone: "Europe/Riga", currencyCode: "EUR" },
  { id: "LT", label: "Lithuania", languageTag: "lt-LT", timeZone: "Europe/Vilnius", currencyCode: "EUR" },
  { id: "UA", label: "Ukraine", languageTag: "uk-UA", timeZone: "Europe/Kyiv", currencyCode: "UAH" },
  { id: "MD", label: "Moldova", languageTag: "ro-MD", timeZone: "Europe/Chisinau", currencyCode: "MDL" },
  { id: "CY", label: "Cyprus", languageTag: "el-CY", timeZone: "Asia/Nicosia", currencyCode: "EUR" },
  { id: "MT", label: "Malta", languageTag: "mt-MT", timeZone: "Europe/Malta", currencyCode: "EUR" },
  { id: "MX", label: "Mexico", languageTag: "es-MX", timeZone: "America/Mexico_City", currencyCode: "MXN" },
  { id: "BR", label: "Brazil", languageTag: "pt-BR", timeZone: "America/Sao_Paulo", currencyCode: "BRL" },
  { id: "AR", label: "Argentina", languageTag: "es-AR", timeZone: "America/Argentina/Buenos_Aires", currencyCode: "ARS" },
  { id: "CL", label: "Chile", languageTag: "es-CL", timeZone: "America/Santiago", currencyCode: "CLP" },
  { id: "CO", label: "Colombia", languageTag: "es-CO", timeZone: "America/Bogota", currencyCode: "COP" },
  { id: "PE", label: "Peru", languageTag: "es-PE", timeZone: "America/Lima", currencyCode: "PEN" },
  { id: "VE", label: "Venezuela", languageTag: "es-VE", timeZone: "America/Caracas", currencyCode: "VES" },
  { id: "UY", label: "Uruguay", languageTag: "es-UY", timeZone: "America/Montevideo", currencyCode: "UYU" },
  { id: "PY", label: "Paraguay", languageTag: "es-PY", timeZone: "America/Asuncion", currencyCode: "PYG" },
  { id: "BO", label: "Bolivia", languageTag: "es-BO", timeZone: "America/La_Paz", currencyCode: "BOB" },
  { id: "EC", label: "Ecuador", languageTag: "es-EC", timeZone: "America/Guayaquil", currencyCode: "USD" },
  { id: "CR", label: "Costa Rica", languageTag: "es-CR", timeZone: "America/Costa_Rica", currencyCode: "CRC" },
  { id: "PA", label: "Panama", languageTag: "es-PA", timeZone: "America/Panama", currencyCode: "PAB" },
  { id: "GT", label: "Guatemala", languageTag: "es-GT", timeZone: "America/Guatemala", currencyCode: "GTQ" },
  { id: "SV", label: "El Salvador", languageTag: "es-SV", timeZone: "America/El_Salvador", currencyCode: "USD" },
  { id: "HN", label: "Honduras", languageTag: "es-HN", timeZone: "America/Tegucigalpa", currencyCode: "HNL" },
  { id: "NI", label: "Nicaragua", languageTag: "es-NI", timeZone: "America/Managua", currencyCode: "NIO" },
  { id: "DO", label: "Dominican Republic", languageTag: "es-DO", timeZone: "America/Santo_Domingo", currencyCode: "DOP" },
  { id: "JM", label: "Jamaica", languageTag: "en-JM", timeZone: "America/Jamaica", currencyCode: "JMD" },
  { id: "TT", label: "Trinidad and Tobago", languageTag: "en-TT", timeZone: "America/Port_of_Spain", currencyCode: "TTD" },
  { id: "BS", label: "Bahamas", languageTag: "en-BS", timeZone: "America/Nassau", currencyCode: "BSD" },
  { id: "BB", label: "Barbados", languageTag: "en-BB", timeZone: "America/Barbados", currencyCode: "BBD" },
  { id: "ZA", label: "South Africa", languageTag: "en-ZA", timeZone: "Africa/Johannesburg", currencyCode: "ZAR" },
  { id: "EG", label: "Egypt", languageTag: "ar-EG", timeZone: "Africa/Cairo", currencyCode: "EGP" },
  { id: "NG", label: "Nigeria", languageTag: "en-NG", timeZone: "Africa/Lagos", currencyCode: "NGN" },
  { id: "KE", label: "Kenya", languageTag: "en-KE", timeZone: "Africa/Nairobi", currencyCode: "KES" },
  { id: "GH", label: "Ghana", languageTag: "en-GH", timeZone: "Africa/Accra", currencyCode: "GHS" },
  { id: "MA", label: "Morocco", languageTag: "ar-MA", timeZone: "Africa/Casablanca", currencyCode: "MAD" },
  { id: "DZ", label: "Algeria", languageTag: "ar-DZ", timeZone: "Africa/Algiers", currencyCode: "DZD" },
  { id: "TN", label: "Tunisia", languageTag: "ar-TN", timeZone: "Africa/Tunis", currencyCode: "TND" },
  { id: "ET", label: "Ethiopia", languageTag: "am-ET", timeZone: "Africa/Addis_Ababa", currencyCode: "ETB" },
  { id: "UG", label: "Uganda", languageTag: "en-UG", timeZone: "Africa/Kampala", currencyCode: "UGX" },
  { id: "TZ", label: "Tanzania", languageTag: "sw-TZ", timeZone: "Africa/Dar_es_Salaam", currencyCode: "TZS" },
  { id: "RW", label: "Rwanda", languageTag: "rw-RW", timeZone: "Africa/Kigali", currencyCode: "RWF" },
  { id: "ZM", label: "Zambia", languageTag: "en-ZM", timeZone: "Africa/Lusaka", currencyCode: "ZMW" },
  { id: "ZW", label: "Zimbabwe", languageTag: "en-ZW", timeZone: "Africa/Harare", currencyCode: "ZWG" },
  { id: "BW", label: "Botswana", languageTag: "en-BW", timeZone: "Africa/Gaborone", currencyCode: "BWP" },
  { id: "NA", label: "Namibia", languageTag: "en-NA", timeZone: "Africa/Windhoek", currencyCode: "NAD" },
  { id: "MZ", label: "Mozambique", languageTag: "pt-MZ", timeZone: "Africa/Maputo", currencyCode: "MZN" },
  { id: "AO", label: "Angola", languageTag: "pt-AO", timeZone: "Africa/Luanda", currencyCode: "AOA" },
  { id: "CM", label: "Cameroon", languageTag: "fr-CM", timeZone: "Africa/Douala", currencyCode: "XAF" },
  { id: "CI", label: "Côte d’Ivoire", languageTag: "fr-CI", timeZone: "Africa/Abidjan", currencyCode: "XOF" },
  { id: "SN", label: "Senegal", languageTag: "fr-SN", timeZone: "Africa/Dakar", currencyCode: "XOF" },
  { id: "MU", label: "Mauritius", languageTag: "en-MU", timeZone: "Indian/Mauritius", currencyCode: "MUR" },
  { id: "MG", label: "Madagascar", languageTag: "mg-MG", timeZone: "Indian/Antananarivo", currencyCode: "MGA" },
  { id: "FJ", label: "Fiji", languageTag: "en-FJ", timeZone: "Pacific/Fiji", currencyCode: "FJD" },
  { id: "PG", label: "Papua New Guinea", languageTag: "en-PG", timeZone: "Pacific/Port_Moresby", currencyCode: "PGK" },
  { id: "WS", label: "Samoa", languageTag: "sm-WS", timeZone: "Pacific/Apia", currencyCode: "WST" },
] as const;
