export type RoomDirectoryItem = {
  id: string;
  label: string;
  ko: string;
  templateId: string;
};

const r = (id: string, label: string, ko: string, templateId: string): RoomDirectoryItem => ({ id, label, ko, templateId });

export const ROOM_DIRECTORY: RoomDirectoryItem[] = [
  r("legal", "Legal", "법률", "legal"),
  r("accounting-tax", "Accounting & Tax", "회계·세무", "accounting"),
  r("finance", "Finance", "금융", "finance"),
  r("insurance", "Insurance", "보험", "insurance"),
  r("business-operations", "Business Operations", "사업운영", "business"),
  r("executive-office", "Executive Office", "경영·대표", "business"),
  r("customer-service", "Customer Service", "고객지원", "business"),
  r("reception", "Reception & Phone", "리셉션·전화", "telecom"),
  r("sales", "Sales", "영업", "business"),
  r("marketing-media", "Marketing & Media", "마케팅·미디어", "marketing"),
  r("hr-recruitment", "HR & Recruitment", "인사·채용", "recruitment"),
  r("project-management", "Project Management", "프로젝트", "business"),
  r("documents-contracts", "Documents & Contracts", "문서·계약", "business"),
  r("esign-approval", "E-sign & Approval", "전자서명·승인", "business"),
  r("real-estate", "Real Estate", "부동산", "realestate"),
  r("property-management", "Property Management", "부동산관리", "propertymanagement"),
  r("construction-trades", "Construction & Trades", "건설·기술공사", "construction"),
  r("architecture-design", "Architecture & Design", "건축·설계", "architecture"),
  r("dream-home-3d", "Build My Dream Home 3D", "AI 꿈의 집 3D 설계", "architecture"),
  r("renovation-home-repair", "Renovation & Home Repair", "리모델링·수리", "construction"),
  r("building-materials", "Building Materials", "건축자재", "buildingmaterials"),
  r("hardware-tools", "Hardware & Tools", "공구·DIY", "hardware"),
  r("medical-clinic", "Medical & Clinic", "의료", "medical"),
  r("dental", "Dental", "치과", "medical"),
  r("allied-health", "Allied Health", "물리치료 등", "medical"),
  r("pharmacy", "Pharmacy", "약국", "medical"),
  r("mental-health", "Mental Health & Counselling", "상담", "consultation"),
  r("aged-care", "Aged Care", "노인복지", "medical"),
  r("disability-support", "Disability Support", "장애지원", "medical"),
  r("education", "Education", "교육", "education"),
  r("ai-tutor", "AI Tutor", "개인교사", "education"),
  r("university-research", "University & Research", "대학·연구", "education"),
  r("music", "Music", "음악", "music"),
  r("dance", "Dance", "댄스", "dance"),
  r("sports", "Sports", "스포츠 팬", "fitness"),
  r("sports-club-team", "Sports Club & Team", "스포츠 팀·클럽", "fitness"),
  r("athlete-coach", "Athlete & Coach", "선수·코치", "fitness"),
  r("fitness-gym", "Fitness & Gym", "피트니스", "fitness"),
  r("travel", "Travel", "여행", "hotel"),
  r("hotel-hospitality", "Hotel & Hospitality", "호텔·숙박", "hotel"),
  r("restaurant-cafe", "Restaurant & Cafe", "식당·카페", "restaurant"),
  r("food-grocery", "Food & Grocery", "식품·마트", "foodgrocery"),
  r("retail", "Retail", "소매", "retail"),
  r("online-store", "Online Store", "온라인쇼핑", "retail"),
  r("marketplace", "Marketplace", "마켓플레이스", "marketplace"),
  r("home-shopping", "Home Shopping", "홈쇼핑", "homeshopping"),
  r("automotive", "Automotive", "자동차", "automotive"),
  r("transport-logistics", "Transport & Logistics", "운송·물류", "logistics"),
  r("manufacturing", "Manufacturing", "제조", "manufacturing"),
  r("agriculture-farming", "Agriculture & Farming", "농업", "agriculture"),
  r("greenhouse-horticulture", "Greenhouse & Horticulture", "온실·원예", "agriculture"),
  r("it-software", "IT & Software", "IT·소프트웨어", "technology"),
  r("ai-automation", "AI & Automation", "AI·자동화", "technology"),
  r("cybersecurity", "Cybersecurity", "보안", "technology"),
  r("telecom-phone", "Telecom & Phone", "통신·전화", "telecom"),
  r("electronics-appliances", "Electronics & Appliances", "전자제품", "electronics"),
  r("website-builder", "Website Builder", "웹사이트 제작", "technology"),
  r("app-development", "App Development", "앱 개발", "technology"),
  r("coding-developer", "Coding & Developer", "개발자", "technology"),
  r("creative-studio", "Creative Studio", "디자인·콘텐츠", "marketing"),
  r("photo-video", "Photo & Video", "사진·영상", "marketing"),
  r("personal-assistant", "Personal Assistant", "개인비서", "custom"),
  r("family", "Family", "가족", "custom"),
  r("personal-finance", "Personal Finance", "개인재무", "finance"),
  r("shopping-assistant", "Shopping Assistant", "쇼핑비서", "retail"),
  r("career-job-search", "Career & Job Search", "취업·경력", "recruitment"),
  r("immigration-visa", "Immigration & Visa", "이민·비자", "migration"),
  r("government-public", "Government & Public Services", "정부·공공", "custom"),
  r("nonprofit-association", "Non-profit & Association", "비영리·협회", "business"),
  r("community", "Community", "커뮤니티", "custom"),
  r("consulting", "Consulting", "컨설팅", "consultation"),
  r("research-intelligence", "Research & Intelligence", "조사·분석", "custom"),
  r("patent-ip", "Patent & IP", "특허·지식재산", "legal"),
  r("compliance-risk", "Compliance & Risk", "규정·리스크", "legal"),
  r("security-safety", "Security & Safety", "안전관리", "technology"),
  r("procurement", "Procurement", "구매·조달", "business"),
  r("inventory-warehouse", "Inventory & Warehouse", "재고·창고", "logistics"),
  r("crm-client-management", "CRM & Client Management", "고객관리", "business"),
  r("billing-payments", "Billing & Payments", "청구·결제", "finance"),
  r("international-trade", "International Trade", "무역", "business"),
  r("import-export", "Import & Export", "수출입", "logistics"),
  r("space-services", "Space Services", "우주서비스", "space"),
  r("satellite-internet", "Satellite Internet", "위성인터넷", "satelliteinternet"),
  r("earth-observation", "Earth Observation", "위성영상", "earthobservation"),
  r("space-research", "Space Research", "우주연구", "spaceresearch"),
  r("environment-sustainability", "Environment & Sustainability", "환경·지속가능성", "custom"),
  r("energy-solar", "Energy & Solar", "에너지·태양광", "construction"),
  r("emergency-disaster", "Emergency & Disaster Support", "재난지원", "custom"),
  r("events-wedding", "Events & Wedding", "행사·웨딩", "hotel"),
  r("beauty-salon", "Beauty & Salon", "미용", "beauty"),
  r("fashion", "Fashion", "패션", "retail"),
  r("pet-care", "Pet Care", "반려동물", "custom"),
  r("hobby", "Hobby", "취미", "custom"),
  r("gaming-esports", "Gaming & Esports", "게임·e스포츠", "custom"),
  r("creator-influencer", "Creator & Influencer", "크리에이터", "marketing"),
  r("translation-languages", "Translation & Languages", "번역·언어", "education"),
  r("news-current-affairs", "News & Current Affairs", "뉴스", "custom"),
  r("personal-research", "Personal Research", "개인리서치", "custom"),
  r("charity-social-support", "Charity & Social Support", "사회지원", "custom"),
  r("custom", "Anything / Custom Room", "맞춤형 Room", "custom"),
];
