export type RoomTemplateField = {
  id: string;
  label: string;
  placeholder?: string;
  options?: string[];
};

export type RoomTemplate = {
  id: string;
  name: string;
  shortDescription: string;
  suggestedAgents: string[];
  fields: RoomTemplateField[];
};

const f = (id: string, label: string, options: string[]): RoomTemplateField => ({ id, label, options });

export const ROOM_TEMPLATES: RoomTemplate[] = [
  { id: "medical", name: "Hospital / Clinic", shortDescription: "Medical, dental, allied health and specialist services", suggestedAgents: ["Reception", "Booking", "Patient Support", "Documents"], fields: [f("specialty", "Clinic / specialty", ["GP", "Dental", "Psychology", "Physiotherapy", "Specialist", "Allied Health", "Other"]), f("contact", "Patient contact", ["Chat", "Phone", "Video", "Email", "Mixed"])] },
  { id: "legal", name: "Legal Office", shortDescription: "Law practice, client intake, documents and case support", suggestedAgents: ["Reception", "Legal Intake", "Documents", "Research"], fields: [f("practice", "Practice area", ["Family", "Property", "Compensation", "Commercial", "Criminal", "Immigration", "General"]), f("team", "Professionals", ["1", "2-3", "4-10", "10+"])] },
  { id: "accounting", name: "Accounting / Tax Office", shortDescription: "Accounting, tax, bookkeeping, payroll and BAS", suggestedAgents: ["Reception", "Accounting Intake", "Document Assistant", "Reminders"], fields: [f("services", "Main services", ["Tax Returns", "Bookkeeping", "GST / BAS", "Payroll", "Company Accounts", "Mixed"])] },
  { id: "finance", name: "Finance / Money Services", shortDescription: "Loans, broking, payments, remittance and FX", suggestedAgents: ["Finance Reception", "Loan Intake", "Document Checker", "AML/KYC Assistant"], fields: [f("service", "Finance service", ["Home Loans", "Business Finance", "Refinance", "Payments", "FX", "Remittance", "Mixed"]), f("customer", "Customer type", ["Individuals", "Small Business", "Companies", "Property Investors", "Mixed"])] },
  { id: "business", name: "Business / Company Office", shortDescription: "General company and professional office operations", suggestedAgents: ["Reception", "Executive Assistant", "Sales", "Operations"], fields: [f("team", "Team size", ["1", "2-5", "6-20", "20+"]), f("departments", "Main departments", ["Reception", "Sales", "Accounts", "Support", "Operations", "Mixed"])] },
  { id: "realestate", name: "Real Estate", shortDescription: "Property sales, leasing and enquiries", suggestedAgents: ["Reception", "Property Enquiry", "Inspection Booking", "Follow-up"], fields: [f("service", "Main service", ["Residential Sales", "Commercial Sales", "Leasing", "Buyers Agent", "Mixed"])] },
  { id: "propertymanagement", name: "Property Management", shortDescription: "Rent, maintenance, inspections and tenant support", suggestedAgents: ["Tenant Support", "Maintenance", "Inspection", "Documents"], fields: [f("priority", "Main workflow", ["Rent", "Maintenance", "Inspections", "Arrears", "All"])] },
  { id: "construction", name: "Construction / Trades", shortDescription: "Builders, contractors and trade services", suggestedAgents: ["Reception", "Quote Assistant", "Scheduling", "Project Coordinator"], fields: [f("trade", "Trade / service", ["Builder", "Electrician", "Plumber", "Carpenter", "Painter", "Multi-trade"])] },
  { id: "buildingmaterials", name: "Building Materials", shortDescription: "Timber, steel, cement, roofing, tiles, plumbing and construction supplies", suggestedAgents: ["Sales", "Quote Assistant", "Stock", "Delivery"], fields: [f("product", "Product area", ["Timber", "Steel", "Cement", "Roofing", "Tiles", "Plumbing", "Electrical", "Mixed"]), f("customer", "Customer", ["DIY", "Trades", "Builders", "Developers", "Wholesale", "Mixed"])] },
  { id: "hardware", name: "Hardware / Tools", shortDescription: "Hardware stores, tools, fasteners and DIY supplies", suggestedAgents: ["Product Finder", "Sales", "Stock", "Orders"], fields: [f("range", "Main range", ["Tools", "Fasteners", "Paint", "Garden", "Electrical", "Plumbing", "Mixed"])] },
  { id: "architecture", name: "Architecture / Design Studio", shortDescription: "Architecture, engineering, interior and 3D design", suggestedAgents: ["Design Assistant", "Project Coordinator", "Documents", "Client Presentation"], fields: [f("design", "Main design work", ["Residential", "Commercial", "Interior", "Engineering", "3D / Visualisation", "Mixed"])] },
  { id: "retail", name: "Retail / Online Store", shortDescription: "Products, orders, returns, delivery and online sales", suggestedAgents: ["Sales", "Customer Support", "Orders", "Returns"], fields: [f("channel", "Sales channel", ["Physical Store", "Online", "Marketplace", "Wholesale", "Mixed"])] },
  { id: "homeshopping", name: "Home Shopping / TV Commerce", shortDescription: "Live shopping, catalogue sales, video commerce and call-in ordering", suggestedAgents: ["Product Presenter", "Sales", "Order Assistant", "Customer Support"], fields: [f("channel", "Shopping channel", ["Live Video", "TV-style", "Mobile App", "Web", "Phone Order", "Mixed"]), f("product", "Product type", ["Home", "Beauty", "Fashion", "Food", "Electronics", "Lifestyle", "Mixed"])] },
  { id: "marketplace", name: "Marketplace / Multi-vendor", shortDescription: "Multi-seller product and service marketplace", suggestedAgents: ["Seller Onboarding", "Buyer Support", "Orders", "Disputes"], fields: [f("market", "Marketplace type", ["Products", "Services", "B2B", "Local", "Global", "Mixed"])] },
  { id: "restaurant", name: "Restaurant / Cafe", shortDescription: "Bookings, menus, takeaway and customer service", suggestedAgents: ["Reception", "Booking", "Order Support", "Menu Assistant"], fields: [f("venue", "Venue type", ["Restaurant", "Cafe", "Takeaway", "Bakery", "Food Court", "Mixed"])] },
  { id: "foodgrocery", name: "Food / Grocery", shortDescription: "Grocery, specialty food, fresh produce and delivery", suggestedAgents: ["Product Finder", "Orders", "Delivery", "Customer Support"], fields: [f("type", "Store type", ["Supermarket", "Grocery", "Fresh Produce", "Specialty Food", "Online Grocery", "Mixed"])] },
  { id: "hotel", name: "Hotel / Travel", shortDescription: "Accommodation, reservations, tours and guest services", suggestedAgents: ["Reservations", "Guest Services", "Travel Planner", "Support"], fields: [f("type", "Business type", ["Hotel", "Motel", "Serviced Apartment", "Travel Agency", "Tour Operator"])] },
  { id: "automotive", name: "Automotive", shortDescription: "Vehicle sales, workshops, repairs and servicing", suggestedAgents: ["Reception", "Service Booking", "Quote Assistant", "Follow-up"], fields: [f("businessType", "Business type", ["Dealer", "Workshop", "Mechanic", "Tyres", "Panel / Body", "Detailing"])] },
  { id: "insurance", name: "Insurance", shortDescription: "Insurance enquiries, claims intake and policy support", suggestedAgents: ["Reception", "Claims Intake", "Policy Support", "Documents"], fields: [f("insuranceType", "Insurance type", ["Home", "Motor", "Business", "Travel", "Life", "Mixed"])] },
  { id: "migration", name: "Migration / Visa Services", shortDescription: "Visa enquiries, client intake and documents", suggestedAgents: ["Reception", "Visa Intake", "Document Assistant", "Booking"], fields: [f("visa", "Main visa service", ["Student", "Partner", "Skilled", "Business", "Visitor", "Mixed"])] },
  { id: "recruitment", name: "Recruitment / HR", shortDescription: "Candidates, vacancies, interviews and HR support", suggestedAgents: ["Candidate Intake", "Job Matching", "Interview Booking", "HR Assistant"], fields: [f("service", "Main service", ["Recruitment", "Labour Hire", "Internal HR", "Executive Search", "Mixed"])] },
  { id: "technology", name: "IT / Software / AI", shortDescription: "Software, SaaS, IT support, cybersecurity and AI services", suggestedAgents: ["Technical Support", "Sales", "Onboarding", "Documentation"], fields: [f("service", "Main service", ["Software", "SaaS", "IT Support", "Cybersecurity", "AI Services", "Mixed"])] },
  { id: "telecom", name: "Telecommunications", shortDescription: "Phone, mobile, internet, SIP, cloud communications and connectivity", suggestedAgents: ["Sales", "Provisioning", "Technical Support", "Billing"], fields: [f("service", "Telecom service", ["Mobile", "Internet", "SIP / VoIP", "Cloud Phone", "Data", "Satellite", "Mixed"])] },
  { id: "electronics", name: "Electronics / Appliances", shortDescription: "Consumer electronics, computers, appliances and support", suggestedAgents: ["Product Advisor", "Sales", "Technical Support", "Warranty"], fields: [f("range", "Product range", ["Computers", "Phones", "TV / Audio", "Appliances", "Smart Home", "Mixed"])] },
  { id: "marketing", name: "Marketing / Media", shortDescription: "Advertising, social media, content and campaigns", suggestedAgents: ["Client Intake", "Content", "Campaign Assistant", "Reporting"], fields: [f("service", "Main service", ["Digital Marketing", "Social Media", "Advertising", "Content", "PR", "Mixed"])] },
  { id: "manufacturing", name: "Manufacturing", shortDescription: "Production, suppliers, orders and quality", suggestedAgents: ["Operations", "Procurement", "Orders", "Quality Assistant"], fields: [f("production", "Production type", ["Food", "Industrial", "Consumer Goods", "Components", "Custom", "Mixed"])] },
  { id: "agriculture", name: "Agriculture / Horticulture", shortDescription: "Farming, greenhouse, crops, nursery and research", suggestedAgents: ["Operations", "Crop Assistant", "Records", "Sales"], fields: [f("type", "Operation type", ["Farm", "Greenhouse", "Nursery", "Research", "Wholesale", "Mixed"])] },
  { id: "logistics", name: "Logistics / Transport", shortDescription: "Freight, deliveries, dispatch, fleet and warehousing", suggestedAgents: ["Dispatch", "Booking", "Tracking", "Customer Support"], fields: [f("service", "Transport service", ["Courier", "Freight", "Trucking", "Warehousing", "Passenger", "Mixed"])] },
  { id: "beauty", name: "Beauty / Salon", shortDescription: "Appointments, services, customer care and reminders", suggestedAgents: ["Reception", "Booking", "Customer Care", "Reminders"], fields: [f("service", "Business type", ["Hair", "Beauty", "Nails", "Spa", "Cosmetic", "Mixed"])] },
  { id: "fitness", name: "Fitness / Gym", shortDescription: "Membership, classes, bookings and coaching", suggestedAgents: ["Reception", "Membership", "Class Booking", "Coach Assistant"], fields: [f("type", "Business type", ["Gym", "Personal Training", "Yoga", "Pilates", "Sports Club", "Mixed"])] },
  { id: "education", name: "Education / Classroom", shortDescription: "School, tutoring, academy, lessons and training", suggestedAgents: ["AI Tutor", "Lesson Planner", "Assessment", "Student Support"], fields: [f("subject", "Subject / training", ["Math", "English", "Languages", "Technology", "Professional Training", "Mixed"])] },
  { id: "music", name: "Music / Vocal Studio", shortDescription: "Music, singing, instruments and performance education", suggestedAgents: ["Music Tutor", "Practice Coach", "Lesson Planner", "Recording Notes"], fields: [f("training", "Training", ["Vocal", "Piano", "Guitar", "Strings", "Wind", "Mixed"])] },
  { id: "dance", name: "Dance / Movement Studio", shortDescription: "Dance, movement and performance training", suggestedAgents: ["Dance Coach", "Lesson Planner", "Practice Assistant"], fields: [f("style", "Dance style", ["Ballet", "K-pop", "Ballroom", "Contemporary", "Hip-hop", "Mixed"])] },
  { id: "consultation", name: "Professional Consultation", shortDescription: "Psychology, coaching, advisory and specialist consultation", suggestedAgents: ["Reception", "Consultation Assistant", "Booking", "Notes"], fields: [f("profession", "Professional service", ["Psychology", "Coaching", "Advisory", "Consulting", "Other"])] },

  { id: "space", name: "Space Services", shortDescription: "Satellite connectivity, Earth observation, space data, research and mission support", suggestedAgents: ["Space Service Advisor", "Satellite Connectivity", "Earth Observation", "Space Data", "Research Assistant"], fields: [f("spaceService", "Space service", ["Satellite Internet / Communications", "Earth Observation Images", "Satellite Data", "Mapping / Remote Sensing", "Weather / Climate Data", "Mission / Research Support", "Space Education", "Mixed"]), f("customer", "Customer type", ["Individual", "Business", "Agriculture", "Construction", "Government", "Research / University", "Education", "Mixed"])] },
  { id: "satelliteinternet", name: "Satellite Internet / Connectivity", shortDescription: "Satellite internet and communications service discovery, comparison and setup support", suggestedAgents: ["Connectivity Advisor", "Provider Comparison", "Setup Support", "Technical Support"], fields: [f("provider", "Provider / network", ["SpaceX / Starlink", "Other Satellite Provider", "Compare Providers", "Not Sure"]), f("use", "Main use", ["Home", "Business", "Remote Site", "Farm", "Marine", "Emergency / Backup", "Mixed"])] },
  { id: "earthobservation", name: "Earth Observation / Satellite Images", shortDescription: "Satellite imagery, land monitoring, mapping and change detection", suggestedAgents: ["Earth Image Finder", "Remote Sensing", "Map Analyst", "Report Assistant"], fields: [f("purpose", "Image purpose", ["Property / Construction", "Agriculture", "Environment", "Disaster", "Infrastructure", "Research", "Education", "Other"]), f("output", "Output", ["Latest Image", "Historical Comparison", "Change Detection", "Map / Report", "Data Export", "Mixed"])] },
  { id: "spaceresearch", name: "Space Research / Education", shortDescription: "Astronomy, space science, satellite research and education", suggestedAgents: ["Space Researcher", "Science Tutor", "Data Assistant", "Project Coordinator"], fields: [f("area", "Area", ["Astronomy", "Satellites", "Earth Science", "Planetary Science", "Space Engineering", "Education", "Mixed"])] },

  { id: "custom", name: "Anything / Custom", shortDescription: "Any Earth or space service not listed above", suggestedAgents: ["AI Room Designer", "Research Assistant", "General Assistant"], fields: [
    { id: "purpose", label: "What do you want this Room to do?", placeholder: "Tell Royal Command in a few words" },
    f("scope", "Scope", ["Personal", "Business", "Government", "Research", "Global", "Space", "Other"]),
  ] },
];

export const COMMON_ROOM_FIELDS: RoomTemplateField[] = [
  { id: "roomName", label: "Room name", placeholder: "Name your Room" },
  f("peopleCount", "How many people normally use the Room?", ["1", "2-5", "6-20", "21-100", "100+"]),
  f("atmosphere", "Preferred atmosphere", ["Professional", "Warm", "Luxury", "Simple", "Modern", "Calm", "Technical"]),
  { id: "specialRequest", label: "Anything else you want?", placeholder: "Optional" },
];
