import {beforeEach,it,expect,vi} from "vitest";
const m=vi.hoisted(()=>({auth:vi.fn(),client:vi.fn(),access:vi.fn(),complete:vi.fn(),runtime:vi.fn(),configured:vi.fn(),ready:vi.fn()}));
vi.mock("@/lib/auth",()=>({getCurrentUser:m.auth}));vi.mock("@/lib/supabase/server",()=>({createClient:m.client}));
vi.mock("@/lib/rooms/room6-trial",async importOriginal=>({...await importOriginal<object>(),trialAccess:m.access}));
vi.mock("@/lib/ai/connectors",()=>({getConnector:()=>({complete:m.complete}),isProviderConfigured:m.configured}));
vi.mock("@/lib/runtime/serverDomainContext",()=>({getServerDomainRuntimeContext:m.runtime}));vi.mock("@/config/countryResolver",()=>({isDomainFeatureReady:m.ready}));
import {POST,GET,PUT} from "./route";
let files:Map<string,string>;
const user="11111111-1111-4111-8111-111111111111",room="22222222-2222-4222-8222-222222222222";
function req(id="33333333-3333-4333-8333-333333333333",provider="openai"){return new Request("https://preview.test/api/room6/trial-chat",{method:"POST",body:JSON.stringify({requestId:id,provider,prompt:"테스트"})});}
beforeEach(()=>{vi.clearAllMocks();files=new Map();const b={list:async(prefix:string,o:{limit:number})=>({data:[...files.keys()].filter(p=>p.startsWith(prefix+"/")).sort().reverse().slice(0,o.limit).map(p=>({name:p.split("/").at(-1)})),error:null}),download:async(p:string)=>({data:new Blob([files.get(p)!]),error:null}),upload:async(p:string,data:string)=>{if(files.has(p))return {error:{message:"already exists"}};files.set(p,data);return {error:null};}};m.access.mockResolvedValue({user:{id:user,countryCode:"AU",defaultLanguage:"ko"},roomId:room,db:{storage:{from:()=>b}}});m.configured.mockReturnValue(true);m.runtime.mockResolvedValue({});m.ready.mockReturnValue(true);m.complete.mockResolvedValue({content:"실제 답변"});});
it("saves and reloads a completed turn and does not call provider twice for same request",async()=>{expect((await POST(req())).status).toBe(200);expect((await POST(req())).status).toBe(200);expect(m.complete).toHaveBeenCalledOnce();const r=await (await GET()).json();expect(r.turns).toHaveLength(1);expect(r.profile.language).toBe("ko");expect([...files.keys()].every(p=>p.startsWith(`${user}/${room}/rc-room6-trial-v1/`))).toBe(true);});
it("reserves before parallel requests and never treats pending as completed",async()=>{let done!:(v:unknown)=>void;m.complete.mockImplementation(()=>new Promise(r=>{done=r;}));const first=POST(req());await vi.waitFor(()=>expect(m.complete).toHaveBeenCalledOnce());expect((await POST(req())).status).toBe(409);done({content:"답"});expect((await first).status).toBe(200);});
it("does not mix another provider history or accept invented external completion",async()=>{await POST(req());await POST(req("44444444-4444-4444-8444-444444444444","anthropic"));const messages=m.complete.mock.calls[1][0].messages;expect(messages).toHaveLength(2);expect(messages[0].content).toContain("no external action tools");});
it("denies disconnected provider before reserving or invoking",async()=>{m.configured.mockReturnValue(false);expect((await POST(req())).status).toBe(503);expect(files.size).toBe(0);expect(m.complete).not.toHaveBeenCalled();});
it("saves country change independently of Korean login language and rejects stale saves",async()=>{const profile={country:"JP",language:"ko",timeZone:"Asia/Tokyo",currency:"JPY"};const put=()=>new Request("https://preview.test",{method:"PUT",body:JSON.stringify({revision:0,profile})});expect((await PUT(put())).status).toBe(200);expect((await PUT(put())).status).toBe(409);expect((await(await GET()).json()).profile).toEqual(profile);});
