export const JAPAN_COUNTRY_PACK = {
  id: "JP",
  name: "Japan",
  locale: "ja-JP",
  languageTag: "ja-JP",
  timeZone: "Asia/Tokyo",
  currencyCode: "JPY",
  phoneCountryCode: "+81",
  dateFormat: "YYYY/MM/DD",
  timeFormat: "24h",
  addressFormat: [
    "postal_code",
    "prefecture",
    "city_ward_town",
    "street_block",
    "building_detail",
  ] as const,
  provincesAndTerritories: [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
  ] as const,
  textDirection: "ltr" as const,
  encoding: "UTF-8" as const,
  addressFields: ["postalCode", "prefecture", "cityWardTown", "streetBlock", "buildingDetail", "country"],
  roomDefaults: {
    clonePolicy: "structure-only" as const,
    cloneCustomerData: false as const,
    cloneMemory: false as const,
    cloneCredentials: false as const,
    cloneSecrets: false as const,
    humanApprovalForExternalActions: true,
  },
  packs: {
    legal: "JP Legal Pack",
    accounting: "JP Accounting & Tax Pack",
    customerSupport: "JP Customer Support Pack",
    technology: "JP Technology / Development Pack",
    learning: "JP Learning Pack",
  },
  policy: {
    globalCoreImmutable: true,
    countryRulesSeparateFromCore: true,
    customerDataIsolationRequired: true,
    customerSecretsNeverCopied: true,
    countrySpecificComplianceMustBeVersioned: true,
  },
} as const;

export type JapanCountryPack = typeof JAPAN_COUNTRY_PACK;
