import {afterEach,expect,it,vi} from 'vitest';
import {LearningConversation} from './learning-conversation';
afterEach(()=>vi.useRealTimers());
function setup(){let text:(s:string)=>void=()=>{},end:()=>void=()=>{};const cancel=vi.fn(),start=vi.fn(),ask=vi.fn(async(_text:string,_signal:AbortSignal)=> 'answer'),speak=vi.fn(async()=>{}),phase=vi.fn(),draft=vi.fn();const engine=new LearningConversation({listen:(t,e)=>{text=t;end=e;return {start,cancel};},ask,speak,phase,draft,stopAudio:vi.fn()});return {engine,ask,speak,phase,draft,start,cancel,text:(s:string)=>text(s),end:()=>end()};}
it('automatically asks once, speaks the answer and returns to listening',async()=>{vi.useFakeTimers();const x=setup();x.engine.start();x.text('question');await vi.advanceTimersByTimeAsync(3000);expect(x.ask).toHaveBeenCalledTimes(1);expect(x.ask.mock.calls[0][0]).toBe('question');expect(x.speak).toHaveBeenCalled();expect(x.start).toHaveBeenCalledTimes(2);x.engine.stop();});
it('resets silence while a student continues speaking and suppresses duplicate end events',async()=>{vi.useFakeTimers();const x=setup();x.engine.start();x.text('first');await vi.advanceTimersByTimeAsync(2000);x.text('first second');await vi.advanceTimersByTimeAsync(2000);expect(x.ask).not.toHaveBeenCalled();x.end();x.end();await vi.advanceTimersByTimeAsync(3000);expect(x.ask).toHaveBeenCalledTimes(1);x.engine.stop();});
it('cancels pending questions and does not speak after user stop',async()=>{vi.useFakeTimers();const x=setup();let resolve:(s:string)=>void=()=>{};x.ask.mockImplementation(()=>new Promise(r=>resolve=r));x.engine.start();x.text('question');await vi.advanceTimersByTimeAsync(3000);x.engine.stop();resolve('late');await Promise.resolve();expect(x.speak).not.toHaveBeenCalled();});
it('recognizes a spoken stop command without calling AI',async()=>{vi.useFakeTimers();const x=setup();x.engine.start();x.text('대화 종료');await vi.advanceTimersByTimeAsync(3000);expect(x.ask).not.toHaveBeenCalled();expect(x.phase).toHaveBeenLastCalledWith('idle');});
it('opens with teaching and then listens without waiting for a manual send',async()=>{const x=setup();x.engine.start('Introduce this lesson');await new Promise(r=>setTimeout(r,0));expect(x.ask).toHaveBeenCalledWith('Introduce this lesson',expect.any(AbortSignal));expect(x.speak).toHaveBeenCalled();expect(x.start).toHaveBeenCalledTimes(1);x.engine.stop();});
