"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Bold, Bot, Check, ClipboardPaste, Copy, Headphones, Link2, List, ListOrdered, MessageSquareText, Mic, Paperclip, Plus, Send, Volume2, VolumeX, Warehouse, X } from "lucide-react";

type Message = { id: string; content: string; authorType?: string; author_type?: string; metadata?: Record<string, unknown>; createdAt?: string; created_at?: string };
type ProviderInfo = { id: string; name: string; available: boolean; configured: boolean };
type ChatResult = { finalAnswer: string; responses: Array<{ provider: string; content: string; latencyMs: number; error?: string }>; comparison: { winners: string[]; notes: string[]; providerScores: Record<string, number> }; blocked?: boolean; latencyMs: number };

const LANGS = ["en", "ko", "ja", "zh", "es", "fr", "de"];
const DEFAULT_AI = ["openai", "anthropic", "google", "xai"];
const VISIBLE_AI_LIMIT = 12;
function initials(name: string) { return name.replace(/[^A-Za-z0-9 ]/g, " ").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "AI"; }

export default function RoomPage() {
  const params = useParams<{ id: string }>(); const roomId = params.id;
  const [messages,setMessages]=useState<Message[]>([]); const [documents,setDocuments]=useState<Array<{id:string;filename:string;sizeBytes?:number;size_bytes?:number}>>([]); const [providers,setProviders]=useState<ProviderInfo[]>([]); const [selected,setSelected]=useState<string[]>(DEFAULT_AI); const [prompt,setPrompt]=useState(""); const [language,setLanguage]=useState("en"); const [loading,setLoading]=useState(false); const [listening,setListening]=useState(false); const [speakerEnabled,setSpeakerEnabled]=useState(false); const [warehouseOpen,setWarehouseOpen]=useState(false); const [warehouseSearch,setWarehouseSearch]=useState(""); const [mode,setMode]=useState<"chat"|"voice">("chat"); const [lastComparison,setLastComparison]=useState<ChatResult|null>(null); const [error,setError]=useState("");
  const bottomRef=useRef<HTMLDivElement>(null); const fileRef=useRef<HTMLInputElement>(null); const textRef=useRef<HTMLTextAreaElement>(null);
  const history=useMemo(()=>messages.filter(m=>(m.authorType||m.author_type)!=="system").map(m=>({role:(m.authorType||m.author_type)==="user"?("user" as const):("assistant" as const),content:m.content})),[messages]);
  const visibleSelected=selected.slice(0,VISIBLE_AI_LIMIT); const hiddenSelectedCount=Math.max(0,selected.length-VISIBLE_AI_LIMIT); const selectedProviders=visibleSelected.map(id=>providers.find(p=>p.id===id)).filter((p):p is ProviderInfo=>Boolean(p)); const filteredProviders=providers.filter(p=>p.name.toLowerCase().includes(warehouseSearch.trim().toLowerCase()));
  async function load(){const [roomRes,provRes]=await Promise.all([fetch(`/api/rooms/${roomId}`),fetch("/api/ai/providers")]);const roomData=await roomRes.json();const provData=await provRes.json();if(roomRes.ok){setMessages(roomData.messages||[]);setDocuments(roomData.documents||[])}const nextProviders:ProviderInfo[]=provData.connectors||[];setProviders(nextProviders);if(typeof window!=="undefined"){const saved=window.localStorage.getItem(`royalcommand:room:${roomId}:selected-ai`);if(saved)try{const ids=JSON.parse(saved) as string[];const valid=ids.filter(id=>nextProviders.some(p=>p.id===id));if(valid.length)setSelected(valid)}catch{}}}
  useEffect(()=>{load()},[roomId]); useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(`royalcommand:room:${roomId}:selected-ai`,JSON.stringify(selected))},[roomId,selected]); useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"})},[messages,loading]); useEffect(()=>()=>{if(typeof window!=="undefined")window.speechSynthesis?.cancel()},[]);
  function speak(text:string){if(!speakerEnabled||typeof window==="undefined"||!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(text.slice(0,1200));u.lang=language==="ko"?"ko-KR":language;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
  function toggleSpeaker(){const next=!speakerEnabled;setSpeakerEnabled(next);if(!next&&typeof window!=="undefined")window.speechSynthesis?.cancel()}
  function toggleListen(){setError("");const w=window as unknown as {SpeechRecognition?:new()=>SpeechRecognition;webkitSpeechRecognition?:new()=>SpeechRecognition};const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){setError("Microphone speech recognition is not supported in this browser.");return}const r=new SR();r.lang=language==="ko"?"ko-KR":language;r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=e=>{setListening(false);setError(`Microphone error: ${e.error||"permission or device problem"}`)};r.onresult=e=>{const t=e.results[0]?.[0]?.transcript||"";setPrompt(p=>p?`${p} ${t}`:t);textRef.current?.focus()};r.start()}
  async function send(e?:FormEvent){e?.preventDefault();if(!prompt.trim()||loading)return;if(!selected.length){setError("Choose at least one AI from the AI Warehouse.");return}setLoading(true);setError("");const currentPrompt=prompt.trim();setPrompt("");setMessages(prev=>[...prev,{id:`temp-user-${Date.now()}`,content:currentPrompt,authorType:"user"}]);try{const res=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({roomId,prompt:currentPrompt,language,providers:selected,history})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Chat failed");setLastComparison(data);await load();speak(data.finalAnswer)}catch(err){setError(err instanceof Error?err.message:"Chat failed")}finally{setLoading(false)}}
  async function onUpload(file:File){const form=new FormData();form.set("roomId",roomId);form.set("file",file);const res=await fetch("/api/documents/upload",{method:"POST",body:form});if(!res.ok){const data=await res.json();setError(data.error||"Upload failed");return}await load()}
  function toggleProvider(id:string){const provider=providers.find(p=>p.id===id);if(provider&&!provider.available){setError(`${provider.name} is in the Royal Command catalog but is not connected yet.`);return}setError("");setSelected(prev=>prev.includes(id)?prev.filter(p=>p!==id):[...prev,id])}
  function wrapSelection(before:string,after=before){const el=textRef.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd,selectedText=prompt.slice(start,end)||"text";setPrompt(`${prompt.slice(0,start)}${before}${selectedText}${after}${prompt.slice(end)}`)}
  function prefixLines(prefix:string){const el=textRef.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd,block=prompt.slice(start,end)||prompt;const replaced=block.split("\n").map((line,i)=>prefix==="1. "?`${i+1}. ${line}`:`${prefix}${line}`).join("\n");if(start===end)setPrompt(replaced);else setPrompt(`${prompt.slice(0,start)}${replaced}${prompt.slice(end)}`)}
  async function copyPrompt(){if(prompt)await navigator.clipboard?.writeText(prompt)} async function pastePrompt(){try{const text=await navigator.clipboard.readText();if(text)setPrompt(prev=>`${prev}${prev?" ":""}${text}`)}catch{setError("Browser paste permission is blocked. Use Ctrl+V instead.")}}
  return <main className="mx-auto flex min-h-screen w-full max-w-7xl flex-col px-4 py-5 md:px-6">
    <header className="relative mb-3 flex min-h-14 items-start justify-between gap-3">
      <Link href="/dashboard" className="pt-1 text-sm text-[var(--muted)]">← Dashboard</Link>
      <h1 className="absolute left-1/2 top-0 -translate-x-1/2 whitespace-nowrap text-3xl" style={{fontFamily:"var(--font-display), serif"}}>Royal Command AI Room</h1>
      <div className="ml-auto flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-white/10 p-1"><button type="button" onClick={()=>setMode("chat")} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-xs ${mode==="chat"?"bg-[var(--gold)] text-black":"text-[var(--muted)]"}`}><MessageSquareText size={15}/> Chat</button><button type="button" onClick={()=>setMode("voice")} className={`flex items-center gap-1 rounded-lg px-3 py-2 text-xs ${mode==="voice"?"bg-[var(--gold)] text-black":"text-[var(--muted)]"}`}><Headphones size={15}/> Voice</button></div><button type="button" onClick={toggleSpeaker} className={`rc-btn rc-btn-ghost !px-3 ${speakerEnabled?"border-[var(--gold)] text-[var(--gold-soft)]":""}`}>{speakerEnabled?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><select className="rc-input w-auto" value={language} onChange={e=>setLanguage(e.target.value)}>{LANGS.map(l=><option key={l} value={l}>{l}</option>)}</select></div>
    </header>
    <div className="grid flex-1 gap-4 lg:grid-cols-[1fr_320px]"><section className="rc-card flex min-h-[72vh] flex-col overflow-hidden">
      {mode==="voice"?<div className="border-b border-[var(--line)] p-4 md:p-6"><div className="mx-auto flex max-w-2xl flex-col items-center rounded-3xl border border-white/10 bg-black/25 p-6 text-center"><Bot size={46}/><h2 className="text-xl font-semibold">Royal Command AI Advisor</h2><button type="button" onClick={toggleListen} className="mt-4 rounded-full bg-[var(--gold)] px-5 py-3 text-sm text-black"><Mic size={18} className="inline"/> {listening?"Listening…":"Speak to Royal Command"}</button></div></div>:null}
      <div className="flex-1 space-y-4 overflow-y-auto p-4 md:p-6">{messages.map(m=>{const type=m.authorType||m.author_type||"user";return <div key={m.id} className={`max-w-[90%] rounded-2xl px-4 py-3 whitespace-pre-wrap ${type==="user"?"ml-auto bg-[var(--navy)]":type==="system"?"bg-black/30 text-[var(--muted)]":"border border-[var(--line)] bg-black/40"}`}><div className="mb-1 text-[10px] uppercase tracking-wider text-[var(--gold-soft)]">{type}</div>{m.content}</div>})}{loading?<div className="text-sm text-[var(--muted)]">Consulting {selected.length} selected AIs…</div>:null}<div ref={bottomRef}/></div>
      <form onSubmit={send} className="border-t border-[var(--line)] p-2 md:p-2.5"><textarea ref={textRef} className="rc-input min-h-44 resize-y text-base" placeholder="Type or speak what you want Royal Command to do…" value={prompt} onChange={e=>setPrompt(e.target.value)} spellCheck onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><div className="mt-1.5 flex min-h-7 flex-nowrap items-center gap-0.5 overflow-x-auto rounded-lg border border-white/10 bg-black/20 px-0.5 py-0.5">
        <div className="flex shrink-0 items-center gap-0.5 pr-1">{selectedProviders.map(p=><button key={p.id} type="button" onClick={()=>toggleProvider(p.id)} className="flex shrink-0 items-center gap-1 rounded-md border border-[var(--gold)] bg-[var(--gold)]/10 px-1.5 py-0.5 text-[10px] leading-none text-[var(--gold-soft)]"><span className="grid h-3.5 w-3.5 place-items-center rounded-full bg-white/10 text-[7px] font-semibold">{initials(p.name).slice(0,1)}</span><span>{p.name}</span><Check size={8}/></button>)}{hiddenSelectedCount>0?<button type="button" onClick={()=>setWarehouseOpen(true)} className="px-1 text-[9px] text-[var(--muted)]">+{hiddenSelectedCount}</button>:null}<button type="button" onClick={()=>setWarehouseOpen(true)} className="ml-0.5 flex items-center gap-0.5 rounded-md border border-white/10 px-1.5 py-0.5 text-[9px] text-[var(--muted)]"><Warehouse size={10}/> AI ({providers.length})</button></div>
        <div className="ml-auto flex shrink-0 items-center gap-0"><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={()=>wrapSelection("**")}><Bold size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={()=>prefixLines("• ")}><List size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={()=>prefixLines("1. ")}><ListOrdered size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={()=>wrapSelection("[","](https://)")}><Link2 size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={copyPrompt}><Copy size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={pastePrompt}><ClipboardPaste size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={()=>fileRef.current?.click()}><Paperclip size={12}/></button><button type="button" className="rounded p-1 text-[var(--muted)]" onClick={toggleListen}><Mic size={12}/></button><button type="submit" className="ml-1 flex items-center gap-0.5 rounded-full bg-[var(--gold)] px-2 py-1 text-[9px] font-bold text-black"><Send size={10}/> Send to {selected.length} AIs</button><button type="button" className="ml-0.5 rounded-full border border-[var(--line)] px-1.5 py-1 text-[9px]" onClick={()=>setWarehouseOpen(true)}>Choose AI</button><button type="button" className="ml-0.5 rounded-full border border-[var(--line)] px-1.5 py-1 text-[9px]" onClick={toggleSpeaker}>{speakerEnabled?"Voice on":"Voice off"}</button></div><input ref={fileRef} type="file" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f)}}/></div>{error?<p className="mt-1 text-sm text-[var(--danger)]">{error}</p>:null}</form>
    </section><aside className="space-y-4"><div className="rc-card p-4"><h2 className="text-xl">Comparison</h2>{lastComparison?<div className="mt-3 text-sm text-[var(--muted)]">Latency: {lastComparison.latencyMs}ms</div>:<p className="mt-3 text-sm text-[var(--muted)]">Choose your AI team and send one prompt to compare responses.</p>}</div><div className="rc-card p-4"><h2 class