// APRA's registered ADI list, updated 10 August 2026. Names are a discovery list,
// not a claim that every institution offers a retail online banking login.
export const australianBanks = [
  "Alex Bank Pty Ltd",
  "AMP Bank Ltd",
  "Australia and New Zealand Banking Group Limited",
  "Australian Military Bank Ltd",
  "Australian Settlements Limited (provides industry services)",
  "Auswide Bank Ltd",
  "Avenue Bank Limited",
  "B&E Ltd (trading as Bank of us)",
  "Bank Australia Limited",
  "Bank of Queensland Limited",
  "Bendigo and Adelaide Bank Limited",
  "Beyond Bank Australia Limited",
  "BNK Banking Corporation Limited",
  "Cairns Penny Savings & Loans Limited (trading as Cairns Bank)",
  "Central Murray Credit Union Limited (trading as Central Murray Bank)",
  "Central West Credit Union Limited",
  "Coastline Credit Union Limited (Trading as Coastline Bank)",
  "Commonwealth Bank of Australia",
  "Community First Credit Union Limited (trading as Community First Bank, Easy Street Financial Services and Illawarra Credit Union)",
  "Credit Union Australia Ltd (trading as Great Southern Bank)",
  "Credit Union SA Ltd",
  "Cuscal Limited (provides industry services)",
  "Defence Bank Limited",
  "Dnister Ukrainian Credit Co-operative Limited",
  "Fire Service Credit Union Limited",
  "First Option Bank Ltd",
  "Gateway Bank Ltd",
  "Goulburn Murray Credit Union Co-operative Limited",
  "Heritage and People's Choice Limited (trading as Heritage Bank, People's Choice Credit Union and People First Bank)",
  "Horizon Credit Union Ltd (trading as Horizon Bank)",
  "Hume Bank Limited",
  "IMB Ltd (trading as IMB Bank)",
  "Indue Ltd",
  "Judo Bank Pty Ltd",
  "Laboratories Credit Union Limited",
  "Macarthur Credit Union Ltd (trading as THE MAC)",
  "Macquarie Bank Limited",
  "Maitland Mutual Limited",
  "Members Banking Group Limited (trading as RACQ Bank)",
  "MyState Bank Limited",
  "National Australia Bank Limited",
  "Newcastle Greater Mutual Group Ltd (trading as Newcastle Permanent, and Greater Bank)",
  "Norfina Limited (trading as Suncorp Bank)",
  "Northern Inland Credit Union Limited",
  "Orange Credit Union Limited (trading as Bank Orange)",
  "Police & Nurses Limited (trading as P&N Bank, and BCU Bank)",
  "Police Bank Ltd (trading as Border Bank and Bank of Heritage Isle)",
  "Police Credit Union Limited",
  "Police Financial Services Limited (trading as BankVic)",
  "QPCU Limited (trading as QBANK)",
  "Queensland Country Bank Limited",
  "Railways Credit Union Limited (trading as MOVE)",
  "Regional Australia Bank Ltd",
  "South West Slopes Credit Union Ltd (trading as SWSBANK)",
  "Southern Cross Credit Union Ltd",
  "Teachers Mutual Bank Limited (trading as Firefighters Mutual Bank, Health Professionals Bank, Teachers Mutual Bank and UniBank)",
  "The Broken Hill Community Credit Union Ltd (trading as Broken Hill Bank)",
  "The Capricornian Ltd Trading as The Capricornian Bank",
  "Traditional Credit Union Limited",
  "Transport Mutual Credit Union Limited",
  "Tyro Payments Limited",
  "Unity Bank Limited (trading as G&C Mutual Bank and Reliance Bank)",
  "Victoria Teachers Limited (trading as Bank First)",
  "Warwick Credit Union Ltd (trading as Darling Downs Bank)",
  "WAW Credit Union Co-Operative Limited (trading as BankWAW)",
  "Westpac Banking Corporation",
  "Woolworths Team Bank Limited",
  "Arab Bank Australia Limited",
  "Bank of China (Australia) Limited",
  "Bank of Sydney Ltd",
  "Heartland Bank Australia Limited",
  "HSBC Bank Australia Limited",
  "ING Bank (Australia) Limited (trading as ING)",
  "Rabobank Australia Limited",
  "Revolut Payments Australia Pty Ltd (trading as Revolut Bank Australia)",
  "Agricultural Bank of China Limited",
  "Bank of America, National Association",
  "Bank of Baroda",
  "Bank of China Limited",
  "Bank of Communications Co., Ltd.",
  "Bank of Taiwan",
  "Barclays Bank PLC",
  "BNP Paribas",
  "Canadian Imperial Bank of Commerce",
  "China Construction Bank Corporation",
  "China Everbright Bank Co., Ltd",
  "China Merchants Bank Co., Ltd",
  "Citibank, N.A.",
  "Cooperatieve Rabobank U.A. (trading as Rabobank)",
  "Crédit Agricole Corporate and Investment Bank",
  "DBS Bank Ltd",
  "Deutsche Bank Aktiengessellschaft",
  "E.SUN Commercial Bank, Ltd.",
  "First Commercial Bank",
  "Hua Nan Commercial Bank, Ltd",
  "Industrial and Commercial Bank of China Limited",
  "ING Bank N.V.",
  "Intesa Sanpaolo SPA",
  "JPMorgan Chase Bank, National Association",
  "KEB HANA Bank",
  "Land Bank of Taiwan Co., Ltd",
  "Mega International Commercial Bank Co., Ltd.",
  "Mizuho Bank, Ltd.",
  "MUFG Bank, Ltd.",
  "NongHyup Bank",
  "Oversea-Chinese Banking Corporation Limited",
  "Royal Bank of Canada",
  "Shinhan Bank Co., Ltd",
  "Societe Generale",
  "Standard Chartered Bank",
  "State Bank of India",
  "State Street Bank and Trust Company",
  "Sumitomo Mitsui Banking Corporation",
  "Taipei Fubon Commercial Bank Co., Ltd",
  "Taishin International Bank Co., Ltd",
  "Taiwan Business Bank, Ltd",
  "Taiwan Cooperative Bank, Ltd",
  "The Bank of New York Mellon",
  "The Hongkong and Shanghai Banking Corporation Limited",
  "The Northern Trust Company",
  "UBS AG",
  "Union Bank of India",
  "United Overseas Bank Limited",
  "Woori Bank"
] as const;
export const verifiedBankSites: Record<string,string> = {
 "Australia and New Zealand Banking Group Limited":"https://www.anz.com.au/personal/internet-banking/",
 "Commonwealth Bank of Australia":"https://www.my.commbank.com.au/netbank/Logon/Logon.aspx",
 "Westpac Banking Corporation":"https://banking.westpac.com.au/",
 "National Australia Bank Limited":"https://www.nab.com.au/personal/online-banking/nab-internet-banking",
 "Macquarie Bank Limited":"https://www.macquarie.com.au/digital-banking/online-banking.html",
 "St.George Bank":"https://www.stgeorge.com.au/online-services/internet-banking",
 "Bank of Melbourne":"https://www.bankofmelbourne.com.au/online-services/internet-banking",
 "BankSA":"https://www.banksa.com.au/online-services/internet-banking",
 "ING Bank (Australia) Limited (trading as ING)":"https://www.ing.com.au/online-banking.html",
 "Bendigo and Adelaide Bank Limited":"https://www.bendigobank.com.au/ways-to-bank/internet-banking/",
 "Norfina Limited (trading as Suncorp Bank)":"https://www.suncorpbank.com.au/",
 "Bank of Queensland Limited":"https://www.boq.com.au/personal/online-banking/internet-banking",
 "HSBC Bank Australia Limited":"https://www.hsbc.com.au/"
};
export const bankNames: Record<string,string> = {
 "Australia and New Zealand Banking Group Limited":"ANZ",
 "Commonwealth Bank of Australia":"CBA (CommBank)",
 "Westpac Banking Corporation":"Westpac",
 "National Australia Bank Limited":"NAB",
 "Macquarie Bank Limited":"Macquarie Bank",
 "St.George Bank":"St.George Bank (Westpac group)",
 "Bank of Melbourne":"Bank of Melbourne (Westpac group)",
 "BankSA":"BankSA (Westpac group)",
 "ING Bank (Australia) Limited (trading as ING)":"ING",
 "Bendigo and Adelaide Bank Limited":"Bendigo Bank",
 "Norfina Limited (trading as Suncorp Bank)":"Suncorp Bank",
 "Bank of Queensland Limited":"Bank of Queensland (BOQ)",
 "HSBC Bank Australia Limited":"HSBC Australia"
};

// The major retail banks are placed first for selection. St.George and its
// sister brands are customer-facing Westpac brands, not separate APRA ADIs.
export const majorAustralianBanks = [
 "Commonwealth Bank of Australia",
 "Westpac Banking Corporation",
 "National Australia Bank Limited",
 "Australia and New Zealand Banking Group Limited",
 "Macquarie Bank Limited",
 "ING Bank (Australia) Limited (trading as ING)",
 "Bendigo and Adelaide Bank Limited",
 "Norfina Limited (trading as Suncorp Bank)",
 "Bank of Queensland Limited",
 "HSBC Bank Australia Limited",
 "St.George Bank",
 "Bank of Melbourne",
 "BankSA"
] as const;
const major = new Set<string>(majorAustralianBanks);
export const orderedAustralianBanks: string[] = [
 ...majorAustralianBanks,
 ...australianBanks.filter(name=>!major.has(name)).sort((a,b)=>a.localeCompare(b,'en-AU'))
];
