import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {MeetingCamera} from './meeting-camera';
import {meetingPreviewText} from '@/lib/locale/meeting-preview';
let stop:ReturnType<typeof vi.fn>,getUserMedia:ReturnType<typeof vi.fn>,close:ReturnType<typeof vi.fn<()=>Promise<void>>>,send:ReturnType<typeof vi.fn<(...args:unknown[])=>Promise<void>>>,result:((r:unknown)=>void)|undefined;
const ctx={clearRect:vi.fn(),save:vi.fn(),restore:vi.fn(),beginPath:vi.fn(),rect:vi.fn(),clip:vi.fn(),drawImage:vi.fn(),globalCompositeOperation:'source-over',filter:'none'};
function make(){return new MeetingCamera({play:vi.fn(async()=>{}),pause:vi.fn(),srcObject:null} as unknown as HTMLVideoElement,{width:1280,height:720,getContext:()=>ctx} as unknown as HTMLCanvasElement,()=>({background:{complete:true,naturalWidth:1672,naturalHeight:941} as HTMLImageElement,deskTop:.73,zoom:.85,offset:0,brightness:1}),vi.fn());}
beforeEach(()=>{vi.useFakeTimers();stop=vi.fn();close=vi.fn(async()=>{});send=vi.fn(async()=>{result?.({image:{},segmentationMask:{}});});getUserMedia=vi.fn(async()=>({getTracks:()=>[{stop}],getVideoTracks:()=>[{addEventListener:vi.fn()}]}));vi.stubGlobal('navigator',{mediaDevices:{getUserMedia}});vi.stubGlobal('window',{SelfieSegmentation:class{setOptions(){}onResults(fn:(r:unknown)=>void){result=fn;}send(...args:unknown[]){return send(...args);}close(){return close();}}});vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn());});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.clearAllMocks();});
describe('local meeting camera privacy and lifecycle',()=>{
 it('does not request camera on construction; requests no microphone on explicit start',async()=>{const camera=make();expect(getUserMedia).not.toHaveBeenCalled();expect(await camera.start()).toBe(true);expect(getUserMedia).toHaveBeenCalledWith(expect.objectContaining({audio:false}));expect(ctx.drawImage).toHaveBeenCalledTimes(4);camera.stop();expect(stop).toHaveBeenCalledOnce();});
 it('releases a camera granted after cancellation',async()=>{let grant!:(v:unknown)=>void;getUserMedia.mockImplementation(()=>new Promise(r=>{grant=r;}));const camera=make();const starting=camera.start();camera.stop();grant({getTracks:()=>[{stop}]});expect(await starting).toBe(false);expect(stop).toHaveBeenCalledOnce();expect(send).not.toHaveBeenCalled();});
 it('propagates denied permission without starting processing',async()=>{getUserMedia.mockRejectedValue(new Error('denied'));await expect(make().start()).rejects.toThrow('denied');expect(send).not.toHaveBeenCalled();});
 it('stops camera when first processed frame times out',async()=>{send.mockImplementation(()=>new Promise(()=>{}));const camera=make();const starting=expect(camera.start()).rejects.toThrow('TIMEOUT');await vi.advanceTimersByTimeAsync(20001);await starting;expect(stop).toHaveBeenCalledOnce();});
 it('does not call a pending close until processing settles',async()=>{let finish!:()=>void;send.mockImplementation(()=>new Promise<void>(r=>{finish=r;}));const camera=make();const starting=camera.start();await vi.advanceTimersByTimeAsync(0);camera.stop();expect(close).not.toHaveBeenCalled();finish();expect(await starting).toBe(false);await Promise.resolve();expect(close).toHaveBeenCalled();});
 it('English removes Korean explanation; unsupported locales use English',()=>{expect(meetingPreviewText('intro','ko')).toMatch(/미리보기/);expect(meetingPreviewText('intro','en-AU')).not.toMatch(/[가-힣]/);expect(meetingPreviewText('intro','fr')).toBe(meetingPreviewText('intro','en'));});
});
