// Background artwork only; all actions remain in the shared button runtime.
export const roomTemplates = [
 {id:'ocean-office',name:'Ocean Office',category:'Office',keywords:'ocean coast modern',image:'/room-designs/ocean-office-v1.webp'},
 {id:'desert-office',name:'Desert Office',category:'Office',keywords:'desert stone warm',image:'/room-designs/desert-office-v1.webp'},
 {id:'grand-library-office',name:'Grand Library Office',category:'Office',keywords:'library classic books',image:'/room-designs/grand-library-office-v1.webp'},
 {id:'forest-office',name:'Forest Office',category:'Office',keywords:'forest nature wood',image:'/room-designs/forest-office-v1.webp'},
 {id:'illustrated-office',name:'Illustrated Office',category:'Illustration',keywords:'illustrated bright city',image:'/room-designs/illustrated-office-v1.webp'},
 {id:'classic-office',name:'Classic Office',category:'Office',keywords:'classic warm wood',image:'/room-designs/classic-office-v1.webp'},
 {id:'office-collection-20260921-01',name:'Harbour Team Office',category:'Office',keywords:'harbour team office',image:'/room-designs/office-collection-20260921-01.webp'},
 {id:'office-collection-20260921-02',name:'Airport Executive Office',category:'Office',keywords:'airport executive office',image:'/room-designs/office-collection-20260921-02.webp'},
 {id:'office-collection-20260921-03',name:'Heritage Library Office',category:'Office',keywords:'heritage library office',image:'/room-designs/office-collection-20260921-03.webp'},
 {id:'office-collection-20260921-04',name:'Garden Studio Office',category:'Office',keywords:'garden studio office',image:'/room-designs/office-collection-20260921-04.webp'},
 {id:'office-collection-20260921-05',name:'Creative Loft Office',category:'Office',keywords:'creative loft office',image:'/room-designs/office-collection-20260921-05.webp'},
 {id:'office-collection-20260921-06',name:'City Finance Office',category:'Office',keywords:'city finance office',image:'/room-designs/office-collection-20260921-06.webp'},
 {id:'office-collection-20260921-07',name:'Coastal Team Office',category:'Office',keywords:'coastal team office',image:'/room-designs/office-collection-20260921-07.webp'},
 {id:'office-collection-20260921-08',name:'Future Tech Office',category:'Office',keywords:'future tech office',image:'/room-designs/office-collection-20260921-08.webp'},
 {id:'office-collection-20260921-09',name:'Nature Lounge Office',category:'Office',keywords:'nature lounge office',image:'/room-designs/office-collection-20260921-09.webp'},
 {id:'office-collection-20260921-10',name:'Skyline Collaborative Office',category:'Office',keywords:'skyline collaborative office',image:'/room-designs/office-collection-20260921-10.webp'},
 {id:'flower-office-20260921-01',name:'Rose Courtyard Office',category:'Flower Offices',keywords:'flowers plants blooming happy rose courtyard office',image:'/room-designs/flower-office-20260921-01.webp'},
 {id:'flower-office-20260921-02',name:'Orchid Conservatory Office',category:'Flower Offices',keywords:'flowers plants blooming happy orchid conservatory office',image:'/room-designs/flower-office-20260921-02.webp'},
 {id:'flower-office-20260921-03',name:'Tulip Canal Office',category:'Flower Offices',keywords:'flowers plants blooming happy tulip canal office',image:'/room-designs/flower-office-20260921-03.webp'},
 {id:'flower-office-20260921-04',name:'Sunflower Workshop Office',category:'Flower Offices',keywords:'flowers plants blooming happy sunflower workshop office',image:'/room-designs/flower-office-20260921-04.webp'},
 {id:'flower-office-20260921-05',name:'Hydrangea Rain Garden Office',category:'Flower Offices',keywords:'flowers plants blooming happy hydrangea rain garden office',image:'/room-designs/flower-office-20260921-05.webp'},
 {id:'flower-office-20260921-06',name:'Bougainvillea Terrace Office',category:'Flower Offices',keywords:'flowers plants blooming happy bougainvillea terrace office',image:'/room-designs/flower-office-20260921-06.webp'},
 {id:'flower-office-20260921-07',name:'Camellia Brick Studio',category:'Flower Offices',keywords:'flowers plants blooming happy camellia brick studio',image:'/room-designs/flower-office-20260921-07.webp'},
 {id:'flower-office-20260921-08',name:'Lavender Alpine Office',category:'Flower Offices',keywords:'flowers plants blooming happy lavender alpine office',image:'/room-designs/flower-office-20260921-08.webp'},
 {id:'flower-office-20260921-09',name:'Lotus Pavilion Office',category:'Flower Offices',keywords:'flowers plants blooming happy lotus pavilion office',image:'/room-designs/flower-office-20260921-09.webp'},
 {id:'flower-office-20260921-10',name:'Dahlia Art Deco Office',category:'Flower Offices',keywords:'flowers plants blooming happy dahlia art deco office',image:'/room-designs/flower-office-20260921-10.webp'},
 {id:'uploaded-office-20260921-01',name:'Royal Command Bright Office',category:'Royal Command',keywords:'royal command bright office',image:'/room-designs/uploaded-office-20260921-01.webp'},
 {id:'uploaded-office-20260921-02',name:'Royal Command Executive Meeting',category:'Royal Command',keywords:'royal command executive meeting',image:'/room-designs/uploaded-office-20260921-02.webp'},
 {id:'uploaded-office-20260921-03',name:'Royal Command Advisory Office',category:'Royal Command',keywords:'royal command advisory office',image:'/room-designs/uploaded-office-20260921-03.webp'},
 {id:'uploaded-office-20260921-04',name:'Royal Command Business Operations',category:'Royal Command',keywords:'royal command business operations',image:'/room-designs/uploaded-office-20260921-04.webp'},
 {id:'uploaded-office-20260921-05',name:'Royal Command Community Office',category:'Royal Command',keywords:'royal command community office',image:'/room-designs/uploaded-office-20260921-05.webp'},
 {id:'uploaded-office-20260921-06',name:'RC Hobby Workshop Collage',category:'Workshop',keywords:'rc hobby workshop collage',image:'/room-designs/uploaded-office-20260921-06.webp'},
 {id:'uploaded-office-20260921-07',name:'Collaboration Design Studio',category:'Studio',keywords:'collaboration design studio',image:'/room-designs/uploaded-office-20260921-07.webp'},
 {id:'illustrated-office-20260921-01',name:'Illustrated Open Plan Office',category:'Illustration',keywords:'illustrated open plan office',image:'/room-designs/illustrated-office-20260921-01.webp'},
 {id:'illustrated-office-20260921-02',name:'Illustrated Executive Collaboration',category:'Illustration',keywords:'illustrated executive collaboration',image:'/room-designs/illustrated-office-20260921-02.webp'},
 {id:'illustrated-office-20260921-03',name:'Illustrated Advisory Office',category:'Illustration',keywords:'illustrated advisory office',image:'/room-designs/illustrated-office-20260921-03.webp'},
 {id:'illustrated-office-20260921-04',name:'Illustrated Analytics Office',category:'Illustration',keywords:'illustrated analytics office',image:'/room-designs/illustrated-office-20260921-04.webp'},
 {id:'illustrated-office-20260921-05',name:'Illustrated Cafe Team Office',category:'Illustration',keywords:'illustrated cafe team office',image:'/room-designs/illustrated-office-20260921-05.webp'},
 {id:'illustrated-office-20260921-06',name:'Five Office Illustration Collage',category:'Illustration',keywords:'five office illustration collage',image:'/room-designs/illustrated-office-20260921-06.webp'},
 {id:'uploaded-office-set-three-20260921-01',name:'Modern Open Office Illustration',category:'Illustration',keywords:'modern open office illustration',image:'/room-designs/uploaded-office-set-three-20260921-01.webp'},
 {id:'uploaded-office-set-three-20260921-02',name:'Creative Team Studio Illustration',category:'Illustration',keywords:'creative team studio illustration',image:'/room-designs/uploaded-office-set-three-20260921-02.webp'},
 {id:'uploaded-office-set-three-20260921-03',name:'Executive Library Illustration',category:'Illustration',keywords:'executive library illustration',image:'/room-designs/uploaded-office-set-three-20260921-03.webp'},
 {id:'uploaded-office-set-three-20260921-04',name:'Legal Library Team Illustration',category:'Illustration',keywords:'legal library team illustration',image:'/room-designs/uploaded-office-set-three-20260921-04.webp'},
 {id:'uploaded-office-set-three-20260921-05',name:'Craft and Technology Workshop Collage',category:'Workshop',keywords:'craft and technology workshop collage',image:'/room-designs/uploaded-office-set-three-20260921-05.webp'},
] as const;
export type RoomTemplate = typeof roomTemplates[number];
export function templateImage(t:RoomTemplate){return t.image;}
