insert into public.rc_service_catalog
(service_key, category, name_ko, name_en, summary_ko, summary_en, pricing_type, currency, price_minor, price_status, parent_service_key, tier_rank, default_included, customer_selectable, sort_order, active, updated_at)
values
('media-ai-video','media','AI 영상 제작','AI Video Studio','주제와 설명을 입력해 대본·장면·음성·자막·영상을 제작하는 연결','Create script, scenes, voice, captions and video from a brief','usage','AUD',null,'tbd',null,10,false,true,10,true,now()),
('media-heygen','media','HeyGen 영상 연결','HeyGen Video Connection','아바타 영상·음성·자막·더빙·번역·립싱크 연결','Avatar video, speech, captions, dubbing, translation and lip-sync connection','custom','AUD',null,'quote','media-ai-video',20,false,true,20,true,now()),
('media-avatar','media','AI 아바타 영상','AI Presenter / Avatar Video','AI 진행자·아바타가 말하는 영상 제작','Create presenter-style avatar videos','usage','AUD',null,'tbd','media-ai-video',30,false,true,30,true,now()),
('media-dubbing','media','영상 더빙·번역','Video Dubbing & Translation','영상 다국어 더빙·자막·립싱크','Multilingual dubbing, captions and lip-sync','usage','AUD',null,'tbd','media-ai-video',40,false,true,40,true,now()),
('media-shorts','media','쇼츠·릴스 제작','Shorts / Reels Production','세로형 짧은 영상 제작','Create short-form vertical video packages','monthly','AUD',null,'tbd','media-ai-video',50,false,true,50,true,now()),
('media-youtube-package','media','YouTube 게시 준비','YouTube Publishing Package','영상·제목·설명·썸네일·태그 게시 준비','Prepare video, title, description, thumbnail brief and tags','monthly','AUD',null,'tbd',null,60,false,true,60,true,now()),
('media-youtube-connect','media','YouTube 채널 연결','YouTube Channel Connection','공식 OAuth/API가 활성화된 계정의 게시 연결','Authorised channel publishing connection where official API/OAuth is enabled','custom','AUD',null,'quote','media-youtube-package',70,false,true,70,true,now()),
('music-sheet','music','악보 라이브러리 연결','Sheet Music Library Connection','합법적인 악보 검색·구매·라이선스 다운로드 연결','Licensed sheet-music search, purchase and library connection','custom','AUD',null,'quote',null,10,false,true,10,true,now()),
('music-learning','music','음악 학습 Room','Music Learning Room','레슨·연습계획·과제·녹음·진도 관리','Lessons, practice plans, assignments, recordings and progress','monthly','AUD',null,'tbd',null,20,false,true,20,true,now()),
('music-practice','music','연습·레퍼토리 관리','Practice & Repertoire Tracker','곡·템포·연습시간·피드백·공연목표 관리','Track pieces, tempo, practice time, feedback and goals','monthly','AUD',null,'tbd','music-learning',30,false,true,30,true,now()),
('music-recording','music','음악 녹음 프로젝트','Recording Project Workspace','테이크·가사·참고곡·믹스·메모 관리','Organise takes, lyrics, references, mixes and notes','monthly','AUD',null,'tbd',null,40,false,true,40,true,now()),
('music-ai-song','music','AI 노래·음악 제작','AI Song / Music Creation','장르·분위기·가사로 음악을 만드는 공급자 연결','Connect approved generative music providers','usage','AUD',null,'tbd',null,50,false,true,50,true,now()),
('music-release','music','음원 출시 준비','Music Release Preparation','마스터·아트워크·메타데이터·출시 체크리스트 준비','Prepare masters, artwork brief, metadata and release checklist','monthly','AUD',null,'tbd',null,60,false,true,60,true,now()),
('sports-general','sports','스포츠 트레이닝 Room','Sports Training Room','목표·훈련·영상·코칭·대회·예약·진도 관리','Goals, training, video, coaching, competition and booking workspace','monthly','AUD',null,'tbd',null,10,false,true,10,true,now()),
('sports-golf','sports','골프 Room','Golf Room','레슨·스윙영상·연습·핸디캡·티타임 요청 관리','Lessons, swing video, practice, handicap notes and tee-time requests','monthly','AUD',null,'tbd','sports-general',20,false,true,20,true,now()),
('sports-football','sports','축구 Room','Football / Soccer Room','훈련·경기일정·영상·코칭·출석·대회 관리','Training, fixtures, clips, coaching, attendance and competitions','monthly','AUD',null,'tbd','sports-general',30,false,true,30,true,now()),
('sports-table-tennis','sports','탁구 Room','Table Tennis Room','드릴·서브·경기영상·코칭·대회 관리','Drills, serves, match video, coaching and tournaments','monthly','AUD',null,'tbd','sports-general',40,false,true,40,true,now()),
('sports-badminton','sports','배드민턴 Room','Badminton Room','풋워크·드릴·경기영상·코칭·대회 관리','Footwork, drills, match video, coaching and tournaments','monthly','AUD',null,'tbd','sports-general',50,false,true,50,true,now()),
('sports-video-analysis','sports','스포츠 영상 분석','Sports Video Analysis','훈련·경기 영상을 분석 공급자와 연결','Connect supported sports video-analysis providers','custom','AUD',null,'quote','sports-general',60,false,true,60,true,now()),
('sports-booking','sports','스포츠 시설·레슨 예약','Sports Venue / Lesson Booking','코트·티타임·레슨·시설 예약 요청','Request courts, tee times, lessons and facilities','monthly','AUD',null,'tbd','sports-general',70,false,true,70,true,now()),
('travel-assistant','travel','여행·예약 비서','Travel & Booking Assistant','여행·식당·활동·티켓을 찾아 비교하고 승인 후 예약','Search and compare travel, dining, activities and tickets before approval','monthly','AUD',null,'tbd',null,10,false,true,10,true,now()),
('travel-flights','travel','항공권 연결','Flight Search / Booking Connection','항공편과 여행사 제안을 비교하는 연결','Compare supported flights and agency offers','custom','AUD',null,'quote','travel-assistant',20,false,true,20,true,now()),
('travel-rail','travel','열차·버스 티켓 연결','Rail / Coach Ticket Connection','열차·버스 표 검색·예약 준비','Search and prepare supported rail or coach tickets','custom','AUD',null,'quote','travel-assistant',30,false,true,30,true,now()),
('travel-hotels','travel','호텔 예약 연결','Hotel Booking Connection','숙박 비교·예약 준비','Compare accommodation and prepare booking','custom','AUD',null,'quote','travel-assistant',40,false,true,40,true,now()),
('travel-restaurants','travel','식당 예약','Restaurant Reservation','지원되는 예약 서비스로 식당 예약 요청','Request restaurant reservations through supported services','monthly','AUD',null,'tbd','travel-assistant',50,false,true,50,true,now()),
('travel-tickets','travel','영화·공연·스포츠 티켓','Events / Movies / Sports Tickets','영화·공연·경기 티켓 검색·구매 준비','Search supported ticket sources before customer approval','custom','AUD',null,'quote','travel-assistant',60,false,true,60,true,now()),
('travel-agency-market','travel','RC 여행사 제안 마켓','RC Travel Agency Offers','등록 여행사가 고객 조건에 맞춰 제안·특가를 보낼 수 있는 구조','Approved travel agencies can respond to briefs or matching offers','custom','AUD',null,'quote','travel-assistant',70,false,true,70,true,now()),
('marketplace-listing','marketplace','RC 중고 Marketplace','RC Community Marketplace','RC가 거래 당사자가 되지 않는 공개 중고물품 게시·검색·연락 공간','Public used-goods listing and contact area; RC is not the sale counterparty','free','AUD',0,'fixed',null,10,true,true,10,true,now()),
('marketplace-seller-verify','marketplace','판매자 확인','Seller Verification','이메일·전화·위험기반 신원 확인과 계정 이력 관리','Email, phone, risk-based identity checks and account history controls','free','AUD',0,'fixed','marketplace-listing',20,true,false,20,true,now()),
('marketplace-emergency-report','marketplace','긴급 신고 센터','Emergency Marketplace Report','사기 의심·급박한 문제를 즉시 신고하고 임시 제한을 시작하는 안전기능','Urgent reporting route that can trigger temporary restrictions during review','free','AUD',0,'fixed','marketplace-listing',30,true,false,30,true,now()),
('marketplace-enforcement','marketplace','Marketplace 징계·제한','Marketplace Enforcement','허위판매·반복피해 확인 시 게시삭제·임시정지·사용정지 조치','Listing removal, temporary restriction or suspension for verified abuse','free','AUD',0,'fixed','marketplace-listing',40,true,false,40,true,now())
on conflict (service_key) do update set
category=excluded.category,
name_ko=excluded.name_ko,
name_en=excluded.name_en,
summary_ko=excluded.summary_ko,
summary_en=excluded.summary_en,
pricing_type=excluded.pricing_type,
currency=excluded.currency,
price_minor=excluded.price_minor,
price_status=excluded.price_status,
parent_service_key=excluded.parent_service_key,
tier_rank=excluded.tier_rank,
default_included=excluded.default_included,
customer_selectable=excluded.customer_selectable,
sort_order=excluded.sort_order,
active=excluded.active,
updated_at=now();
