import rows from './practical-60.json';
export const PRACTICAL_COURSE='ai-tools-60-preview-v1';
export const PRACTICAL_TUTOR_NOTES='This is the approved 30-day, 60-lesson practical TEST course. Teach asking AI in natural language: task, context/data, output format and checks. Give one small action, wait for the learner to try it, inspect their actual output, then suggest one revision and recheck. Never equate listening, copying a prompt or your own demonstration with learner execution. Tools named in lessons are external services, NOT automatically connected to RC. Never claim to execute them or view their results. Ask for a non-sensitive result or an honest description. Account, region, credits and capabilities vary; use an available equivalent if necessary and record the substitution. If generation cannot run, call it prompt planning, not completed generation. Do not activate accounts, subscribe, publish, send messages, book or pay. This course has no active assessment or certificate issuance. Drafts are local to this browser and course. Ignore legacy interface locations when they conflict: in V4 use the existing numbered lesson list and teacher controls, not a claimed button beside the day selector. Teach only one step at a time.';

const notice={en:'Fictional reading club: Saturday at 10 am in the practice room. Bring one book and a notebook. The end time is undecided.',ko:'가상 독서 모임: 토요일 오전 10시, 장소는 연습실. 책 한 권과 공책을 가져온다. 종료 시간은 미정이다.'};
const plans={en:'Fictional plan A: 4 people, 20 minutes, cost $0, bring a book and notebook. Plan B: 4 people, 30 minutes, cost $10, bring printed extracts and pens. Both take place in the practice room; the date is undecided.',ko:'가상 행사안 A: 4명, 20분, 비용 0달러, 책과 공책 준비. B: 4명, 30분, 비용 10달러, 발췌 인쇄물과 펜 준비. 장소는 모두 연습실이며 날짜는 미정이다.'};
const script='This is a fictional practice meeting for a reading club. Four people will meet in the practice room on Saturday at ten in the morning. Please bring one book and a notebook. Minsu will prepare the invitation by Friday. Jiyeon will check the room. The end time and the date of our next meeting have not been decided. We will not collect payments or contact any real customers.';
function sample(n:number,ko:boolean){
 if(n===10)return ko?'가상 메모: 이름 김연습, 주소 연습시 가상로 12번지, 토요일 책 한 권 준비. AI에 넣기 전에 이름은 고객A, 주소는 연습시로 직접 바꾸세요.':'Fictional note: Alex Example, 12 Practice Street, Sample City; bring one book on Saturday. Before using AI, replace the name with Customer A and the address with Sample City.';
 if(n===13||n===23)return ko?notice.ko:notice.en;
 if(n===14)return ko?'가상 문서 1쪽: 독서 모임 참가 신청 마감은 금요일 오후 5시다. 모임은 토요일 오전 10시 연습실에서 시작한다.\n가상 문서 2쪽: 참가자는 책 한 권과 공책을 준비한다. 종료 시간은 아직 정하지 않았다.':'Fictional page 1: Reading club registration closes Friday at 5 pm. The meeting starts Saturday at 10 am in the practice room.\nFictional page 2: Participants bring one book and a notebook. The end time has not been decided.';
 if([24,49,50].includes(n))return ko?plans.ko:plans.en;
 if(n===27)return (ko?'아래 영어 원고를 본인 목소리로 약 30초 녹음하세요. 녹음 시간이 길어지면 자연스럽게 읽되 단어를 생략하지 마세요. 이 테스트에는 녹음된 예제 파일이 없으며 아래는 녹음용 원고입니다.\n':'Record the following fictional script in your own voice for about 30 seconds. Read naturally without omitting words. This test supplies a script, not a prerecorded audio file.\n')+script;
 if(n===28)return ko?'27번에서 직접 녹음하고 교정한 전사문을 사용하세요. 원음이 없다면 위조하지 말고 전사 실습부터 진행하세요.':'Use the corrected transcript from lesson 27. If there is no recording, do that exercise first rather than inventing audio evidence.';
 return '';
}
function body(row:typeof rows[number],ko:boolean){
 const n=Number(row.id.slice(1)),data=sample(n,ko);
 const timing=ko?'15분 실습: 설명 2분 · 요청 예시 2분 · 직접 실행 7분 · 수정 3분 · 확인 1분. 계정 준비와 생성 대기 시간은 별도입니다.':'15-minute practice: explanation 2 min, example 2, your action 7, revision 3, review 1. Account setup and generation waiting are extra.';
 const intro=ko?'AI에게 부탁하는 말은 특별한 컴퓨터 언어가 아닙니다. 할 일, 필요한 상황과 자료, 원하는 답 모양을 평소 말로 알려주세요. 오늘은 아래 요청에서 조건 하나를 찾아 내 상황에 맞게 바꿔봅니다.':'An AI request is ordinary language. Describe the task, necessary context and data, and the shape of the answer. Find one condition in today’s example and adapt it yourself.';
 const task=ko?row.taskKo:row.task;
 const adaptedTask=n===27?(ko?'아래 가상 영어 원고를 직접 녹음하고 이용 가능한 AssemblyAI Playground에서 전사해 보세요.':row.task):task;
 const check=n===60?(ko?'다음 주 활용 계획을 작성하세요. 최종 시험은 별도 30분·70점 기준으로 설계되어 있으며 이 테스트 과정에서는 아직 시험·수료증을 발급하지 않습니다.':row.check):(ko?row.checkKo:row.check);
 return [timing,intro,(ko?'오늘 직접 해볼 요청과 행동\n':'Today’s request and action\n')+adaptedTask,data?(ko?'실습 자료\n':'Practice data\n')+data:'',(ko?'직접 실행\n':'Try it yourself\n')+(ko?'해당 AI 또는 편집 도구를 별도 창에서 열고 위 요청을 실행하세요. 앞선 결과를 고치는 수업은 이전 레슨의 실제 결과를 함께 사용하세요. 실제로 받은 답이나 만든 파일을 확인한 뒤, 아래 실습 기록에 처음 요청과 결과를 적으세요. RC 튜터는 질문과 수정 방법을 안내하며 외부 도구를 대신 실행하지 않습니다.':'Open the relevant AI or editor in another window and perform the action. For a follow-up lesson, include your actual previous result. Inspect the answer or file and record your request and result below. The RC tutor coaches your questions and revisions; it does not operate external tools for you.'),(ko?'확인 기준\n':'Check the result\n')+check,(ko?'다시 부탁하기\n':'Ask for a revision\n')+(ko?'“이 결과에서 [바꿀 부분]만 [원하는 모습]으로 고쳐줘. [유지할 내용]은 그대로 두고, 확인하지 못한 것은 모른다고 말해줘.” 대괄호를 직접 채워 한 번 더 실행하고 전후를 비교하세요. 문제가 없다면 왜 맞는지 설명하세요.':'“Change only [specific part] to [desired result]. Keep [unchanged facts] as they are, and say when something is unknown.” Fill in the brackets, try again, and compare. If no correction is needed, explain why the result meets your criteria.'),(ko?'실습 기록\n':'Practice record\n')+(ko?'처음 요청 / 실제 결과 / 수정 요청 / 다시 확인한 내용 / 실행하지 못한 부분을 남기세요. 튜터에게는 “여기까지 직접 해봤어요. [결과]. 다음 한 단계만 알려줘”라고 질문하세요. 읽기만 했거나 질문만 준비했다면 실행 완료로 적지 않습니다.':'Record the first request, actual output, revision, recheck and anything unexecuted. Ask the tutor: “I tried this: [result]. Give me just the next step.” Reading or preparing a prompt alone is not execution.'),(ko?'이용 조건\n':'Availability\n')+(ko?'외부 서비스의 계정·지역·요금·크레딧은 별도입니다. 자동 결제나 가입을 하지 마세요. 이용할 수 없으면 가능한 동등 기능으로 연습하고 사용한 도구를 기록하세요. 생성 자체가 불가능하면 “요청문만 준비, 실행 미완료”로 남기세요.':'External accounts, regions, fees and credits are separate. Do not automatically subscribe or pay. Use an available equivalent and record it if needed; if no generation can run, record “prompt prepared, execution incomplete”.')].filter(Boolean).join('\n\n');
}
export const practicalLessons=rows.map(row=>({...row,body:body(row,false),ko:body(row,true)}));
export const practicalGroups=rows.map((row,i)=>({id:String(i+1).padStart(3,'0'),day:row.day,koTitle:row.koTitle,sources:[row.id]}));
